dotnet/xharness

azure-pipelines.yml
Promote jobs to stages, don't do debug builds on internal, and add Microbuild property to hopefully fix signing on internal
=> Try out PR flow

.gitattributes
Repo was initialized with arcade scripts having LF and they cannot be executed on Linux
=> Force LF EOLs in shell scripts

src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Common/ICommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Common/PackageCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Common/PackageCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Common/TestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Common/TestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Common/XHarnessCommand.cs, src/Microsoft.DotNet.XHarness.CLI/iOS/iOSPackageCommand.cs, src/Microsoft.DotNet.XHarness.CLI/iOS/iOSPackageCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommandArguments.cs
Common arguments and their validation is now handled in one place for Android and iOS platforms.
This should help make sure our Android and iOS CLI won't digress much and should help reduce the need to write validation boilerplate twice. It also allows to write async implementation of the commands which was cumbersome to do before.
=> Unify common argument parsing for test/package commands

eng/install-mlaunch.sh, mlaunch.version
The script downloads given revision of the `mlaunch` tool from https://github.com/xamarin/macios-binaries.
This script will be used when setting up our dev env and also when bundling the tool in the pipeline
=> Add script for installing mlaunch

CODE_OF_CONDUCT.md, README.md
For more details, see [PR16](https://github.com/dotnet/org-policy/blob/master/doc/PR16.md).
=> Fix links to Code of Conduct

src/Microsoft.DotNet.XHarness.Tests.Runners/Microsoft.DotNet.XHarness.Tests.Runners.csproj
I was trying to build in Ubuntu and the build broke because of case conflict between the csproj and the folder name. Not sure how MacOS builds ok but fixing this.
Also removing unnecessary sections from csproj
=> Fix case sensitivity issue (Xunit vs xUnit) in dotnet build

.gitignore, global.json, src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This should probably be in Microsoft.DotNet.XHarness.Android but I couldn't get it to end up in the Nupkg without putting it in the CLI project
I asked a couple folks, also tagging @rainersigwald  in case he has ideas.  Basically I'd like to have this ADB stuff be in the referenced Android project and not the CLI, and I failed to make that happen so I just stuck it in the CLI project for now.  Is this fixable?
=> Download and unzip ADB from android tools

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Should fix build errors.  I locally verified that the lookup path behavior does not work on Windows too. 
Was meant to be part of https://github.com/dotnet/xharness/pull/27
=> Move ADB.exe to try to suppress NU5100

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs
Allow clients to set the minimun log level to be used by the logging in
the test runner.
fixes: https://github.com/dotnet/xharness/issues/44
=> [Runners] Expose the minimum log level to clients.

src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/TestRunResult.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/iOSApplicationEntryPoint.cs
Add two events that notify when the runner started and when it
completed. The completed event will provide information of the results
of the run.
Later we can look at adding event for each of the tests starting and
completing, which is possible, but we are not going to add events that
we have not been asked to add. KISS
fixes: https://github.com/dotnet/xharness/issues/36
=> [Runners] Add events to notify that a test run started and completed.

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/Core/TestResult.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/Core/TestRunner.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
Add event to the base class and each of the runner implementations will
call it using the provided protected methods.
Expose the events via the ApplicationEntryPoint base class that will
connect to the runner and fwd the events.
fixes: https://github.com/dotnet/xharness/issues/50
=> [Runners] Provide events to notify when a test has started or completed.

eng/download-mlaunch.ps1
There are two places where the files are copied from the checked out repo and one was copying the whole folder instead of files inside.
=> Fix mlaunch path in NuGet when mlaunch is not from cache

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
Add a default category filter on [ActiveIssue] ignoring the url given in
the trait. This will ensure that ActiveIssues from netcore are not
executed.
fixes: https://github.com/dotnet/xharness/issues/53
=> [Runners] Add the default ActiveIssue category.

src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
The OnTestStarted was being called in the HandleAfterTestStarting. That
means that the event might not be raised if there is an issue with the
test setup, making it hard to track. Moved the call to the
HandleBeforeTestStarting to notify the test is going to strat which will
execute before any issue occurs.
fixes: https://github.com/dotnet/xharness/issues/54
=> [Runners] Raise the start event before the tests executes.

src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/IProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS/AppInstaller.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, src/Microsoft.DotNet.XHarness.iOS/AppUninstaller.cs
This is not a final fix but rather unblock for others.
More information about the hang here:
https://github.com/dotnet/xharness/issues/73
=> Prevent hang of XHarness when Listener doesn't initialize fully

tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
PR build didn't catch it because tests were NUnit and ignored. Started failing once we moved to XUnit. 2 separate PRs but together they failed the internal pipeline
=> Fix failing unit tests

src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Mlaunch/Arguments.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListenerFactory.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/TcpTunnel.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/TunnelBore.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/common/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/common/TestRunner/Core/TcpTextWriter.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/iOSApp/ViewController.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/tvOSApp/ViewController.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleListenerFactoryTest.cs
Add the basic classes that are needed to support the creation of tcp
tunnels to the devices. A following commit will provide the required CLI
option and integration to the runner to support this.
=> [iOS] Add basic classes to support the usage of tunnels.

src/Microsoft.DotNet.XHarness.CLI/Common/XHarnessCommand.cs
When getting Helix logs from running XHarness, it is polluted with control characters around `[info]` and `[fail]` and such colouring, so adding a feature to disable that
=> Control logging features through env variables

src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListenerFactory.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
By default, use the tcp tunnel since it will be more reliable and easier
to setup in the CI. Nevertheless, allow user to state that they want to
use the network.
Updated tests both on sim runs, to make sure no tunnles are created and
on devices.
=> [iOS] Add support for tunnels when running on devices.

src/Microsoft.DotNet.XHarness.CLI/Common/XHarnessCommand.cs, src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommandArguments.cs
Add a more verbose error when the user does not provide the correct
target to the command.
fixes: https://github.com/dotnet/xharness/issues/82
=> [iOS] Add a more useful message when a user gets the target wrong.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/iOSApp/ViewController.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/tvOSApp/ViewController.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestImporter/Templates/Managed/Resources/src/watchOS/Extension/InterfaceController.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
During the refactor we removed the env vars that are passed to the
runners to decide if xml is used and the jargon to use. The env
paramenters have been added and tests updated. Now the runners will get
notified that xml is used (always) and the jargon (default to xunit).
fixes: https://github.com/dotnet/xharness/issues/98
fixes: https://github.com/dotnet/xharness/issues/77
=> [iOS] Ensure that we do generate xml when we call the CLI.

src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/Microsoft.DotNet.XHarness.Tests.Runners.csproj, src/Microsoft.DotNet.XHarness.Tests.Runners/iOSApplicationEntryPoint.cs
We forgot to update the applicaiton entry points to consider the usage
of xunit.
fixes: https://github.com/dotnet/xharness/issues/111
=> [Runners] Respect the usage of xunit.

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListenerFactory.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleListenerFactoryTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Remove the need to use a bool. Allow the factory to take a null tunnel
bore (less memory used) and add a property that will tell use if the
factory will use a tunnel bore.
=> [iOS] Improve the TunnelBore API.

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs, src/Microsoft.DotNet.XHarness.iOS/ErrorKnowledgeBase.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/ErrorKnowledgeBaseTests.cs
If a user tries to execute the test command with an application and
the wrong device arch, do notify him since we do know is an expected
error.
Sample output:
```
info: test[0]
Starting test for ios-device targeting XQAiPodTouch5f..
info: test[0]
Installing application 'MonoTouchTest' on  on device 'XQAiPodTouch5f'
fail: test[0]
Failed to install the app bundle (exit code=1): IncorrectArchitecture: Failed to find matching arch for 64-bit Mach-O input file /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.Z91Igw/extracted/monotouchtest.app/monotouchtest
XHarness exit code: -43
```
fixes: https://github.com/dotnet/xharness/issues/88
=> [iOS] If the user tries to install the app in the wrong arch, let him know.

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
Check what targets are passed to the CLI and do not use tunnels in that
case.
fixes: https://github.com/dotnet/xharness/issues/126
=> [iOS] If we use simulators do not use a tunnel.

src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessVersionCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Program.cs
Add a version command that via reflection will get the xharness version.
More data can be added, currently the version printed is:
```bash
dotnet tool xharness version
xharness version 1.0.0-dev (Microsoft.DotNet.XHarness.CLI.exe)
InstalledDir:
/Users/mandel/Xamarin/xharness/artifacts/bin/Microsoft.DotNet.XHarness.CLI/Debug/netcoreapp3.1/Microsoft.DotNet.XHarness.CLI.dll
```
fixes: https://github.com/dotnet/xharness/issues/110
=> [Common] Add version command.

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/Core/TestRunner.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/IgnoreFileParser.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitFilter.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitFilterType.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs, tests/Microsoft.DotNet.XHarness.Tests.Runners.Tests/xUnit/XUnitFilterTests.cs
We support traits from the very first release, those have to be passed in
a file that is provided by the child of the entry point:
IgnoreFilesDirectory.
That directory can contain two diff files:
* xunit-excludes.txt
* nunit-excludes.txt
I have updated the docs to describe what should be done since is the
root of the misscommunication.
fixes: https://github.com/dotnet/xharness/issues/137
=> [Runners] Do not filter per Attr, make client use traits.

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
A parallel change was all that linux needed.  I'm still working on getting this to a mac to try it.
=> MacOS Support - include native adb binary

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs
Expose the property so that we can show which of the tests got skipped.
fixes: https://github.com/dotnet/xharness/issues/141
=> [Runners] Expose a property to allow to log the skipped tests.

src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformation.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/PlistExtensions.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestReporterTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Utilities/PListExtensionsTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Add code that will allow to parse the arch of a bundled app and a
project this will later help to use the correct device when the device
name is not provided.
We yet do not select the correct arch, this is the first step to do so.
=> [iOS] Add support to parse the arch of a csproj or a plist.

src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
I was able to build the app bundle inside the runtime repo and it was missing the `UIRequiredDeviceCapabilities` property which made XHarness crash
=> [iOS] Fix getting information about 32 bit support

azure-pipelines.yml
This reverts commit 08b0461a25241aa77124185d58cc935f2a9f66bd.
Looks like it was fixed already: https://github.com/dotnet/arcade/issues/5328
=> Revert "Disable signing validation to unblock the pipeline (#99)"

src/Microsoft.DotNet.XHarness.Tests.Runners/Microsoft.DotNet.XHarness.Tests.Runners.csproj, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/TestCaseExtensions.cs, tests/Microsoft.DotNet.XHarness.Tests.Runners.Tests/xUnit/XUnitFilterTests.cs
The ActiveIssue discoverer does have a bug in which it does not add the
traits on Android or iOS. The fix was landed here:
https://github.com/dotnet/arcade/pull/5425 but this commit adds a
workaround. Issue https://github.com/dotnet/xharness/issues/156 to
track the workaround and make sure it is removed.
fixes: https://github.com/dotnet/xharness/issues/53
PS: This time it really fixes the issue ;)
=> [Runners] Workaround to discover all the active issues.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/XHarnessCommandArguments.cs
Fixes: https://github.com/dotnet/xharness/issues/154
=> Allow the verbosity to be passed without a value

src/Microsoft.DotNet.XHarness.Android/AdbExitCodes.cs, src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/ApkHelper.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
Today I learned that our emulators are set up x86 only while Runtime team has been primarily been building for x86-x64.  Once we start using real devices we'll need arm64-v8a apps to match.
This change makes it so either the user can specify the arch to run on (--device-arch) and get an error if no such device is available, _or_ leave this out and have it be guessed from the contents of the /lib/ folder of the apk itself.  
Also handles the slightly different non-error failure message from uninstalling an app that isn't there on an emulator versus real device.
=> Changes needed to deal with arch issues

src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
If a test fails and the exception type is SkipTestException, then the runner will flag that as a skipped test.  This is to support tests that depend on something in the xunit pipeline that may not be supported on mobile.  We don't want to have to go into every test and mark ConditionalFact/Theory.
=> Adds support for skipping tests when SkipTestException is raised

src/Microsoft.DotNet.XHarness.iOS.Shared/IResultParser.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
Not all the loggers support the FullPath property and that will result
in runtime exceptions. On the other hand, they all support the GetReader
methods, so switch to that. We keep the path one since is nice for
tests.
Related iOS PR: https://github.com/xamarin/xamarin-macios/pull/8534
=> [iOS] Ensure that when we use other loggers, we can generate xml failures.

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS/AppInstaller.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppInstallerTests.cs
The FindDevice method returns the first device found, but will not
filter over the architecture. Move to use LoadDevices and then use the
collections to use the first device that matches the desired arch.
With this commit, xharness will pick the **correct** device if two different
devices are present in the host.
fixes: https://github.com/dotnet/xharness/issues/86
=> [iOS] Ensure we do select devices according to their architecture.

src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs
Currently Runtime teams and ADO reporting all uses XUnit, so make this a default.  Eventually we'll clean the duplicated enums up and support this from cmd line
=> Make XmlVersion.xUnit default

src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
…  otherwise we may not be able to get a value for architecture used.
=> Move WaitForDevice() above GetDeviceToUse()

tools/Microsoft.DotNet.XHarness.SimulatorInstaller/Microsoft.DotNet.XHarness.SimulatorInstaller.csproj, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/Program.cs, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/SimulatorInstaller.sln, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/runtimeconfig.template.json
This command line tool allows management of Xcode iOS/WatchOS/tvOS Simulators on MacOS.
It is used for automated update of OSX servers.
Originally taken from: https://github.com/xamarin/xamarin-macios/blob/master/tools/siminstaller/Program.cs
It is packaged as a dotnet tool
=> Add the Microsoft.DotNet.XHarness.SimulatorInstaller project

src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/iOSApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Mlaunch/EnviromentVariables.cs
This is a step fwd allowing user to run just those tests that match a
filter or filters. To support that we first want to be able to ignore
all tests and later provide the inclusion filters.
This is related to issue https://github.com/dotnet/xharness/issues/144
=> [Runners] Allow to specify to the test app not to run all tests.

azure-pipelines.yml
… so if this comes back we'll have a binlog.
The problem was in the GH repo itself, along with AzDO changing their response for when giving secrets to forks is turned off
=> Remove hard coded sleep and set_BuildConfig 

src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/integration-tests/helix-payload/osx-helix-payload.sh
Somehow the files are this:
```
+ ls -la /tmp/helix/working/A97E097D/w/AD160905/uploads
total 6424
drwxr-xr-x  9 helix-runner  wheel      288 May 14 06:08 .
drwxr-xr-x  7 helix-runner  wheel      224 May 14 06:08 ..
-rw-r-----  1 root          wheel  3223956 May 14 06:08 iPhone X (iOS 13.4) - created by xharness.log
-rw-r--r--  1 root          wheel        0 May 14 06:08 mlaunch-stderr-20200514_060839.log
-rw-r--r--  1 root          wheel        0 May 14 06:08 mlaunch-stdout-20200514_060839.log
-rw-r--r--  1 root          wheel     6133 May 14 06:08 run-Simulator_iOS64.log
-rw-r--r--  1 root          wheel    42752 May 14 06:08 simulator-list-20200514_060822.log
-rw-r--r--  1 root          wheel     3848 May 14 06:08 test-ios-simulator-64-20200514_060821.log
-rw-r--r--  1 root …
```
=> Fix file permissions for uploads of integration tests

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
With some help from @akoeplinger and some messing around with systemctl commands I think I've solved the "wait for online' issue.  Also added logging for shortMsg, a magical property bag value that seems to come up when an instrumentation crashes.
=> More offline emulator fun

src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs
Logger can definitely be set to null, so in order for classes that implement and override this property and return null they need to set it as nullable. However the nullable annotation needs to match on the abstract member and the override.
cc: @MattGal @EgorBo @akoeplinger @mandel-macaque
=> Fix nullability annotation in AndroidApplicationEntryPoint Logger

src/Microsoft.DotNet.XHarness.Tests.Runners/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/iOSApplicationEntryPoint.cs
There was an issue with the ownership of the IDisposable objects. We
cannot be as smart as we want. Move back to the if statement, do not
default the writer to null.
fixes: https://github.com/dotnet/xharness/issues/199
=> [Runners] Make sure that we dispose things correctly.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSPackageCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/AggregatedLog.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
Add support for the lldb feature in mtouch. User can pass a new flag to
state that lldb should be enabled, the CLI will then provide a command to
copy paste to access the lldb session.
The aggregated log was created to state which of the ILogs that was
passed should be considered the default log and therefore the one to
return the FullPath and the StreamReader.
When the flag is pass the user will get the following:
While if the flag was found but not set by the current xharness execution, it will be respected but a warning will be printed:
=> [iOS] Allow users to use lldb to debug issues in test applications.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/TestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/Core/TestRunner.cs, src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Mlaunch/EnviromentVariables.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Add new parameters to allow to tell the runners to skip all tests and
just run a subset of them via:
-method: The fullname of the method to execute.
-class: The fullname of the test class to execute.
Both allw to be used more than once.
fixes: https://github.com/dotnet/xharness/issues/144
=> [Runners] Allow to provide specific tests and test classes.

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
I can't repro [this error](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-arcade-refs-heads-prvysoky-xharness-io432a676f47944fefa8/xharness-System.Numerics.Vectors.Tests-x86/console.ca83ad82.log) but I know it's out there.  
My approach is to try longer (not the problem in this case, but this is an absolutely breaking problem for > 1 device machines), print out the outputs in case of failure, and tighten up the condition for device listing. I may introduce retry at a different layer if this doesn't work.
=> Improve retry and logging around adb devices

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
I tried this enough times to finally see the output when it finds no devices.   Also address concurrency issue noted occasionally on the process output stringbuilders.
=> Improve polling wait loop for devices -l 

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Collections/BlockingEnumerableCollection.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/ISimulatorDevice.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleFileListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleHttpListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/TcpTunnel.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/CaptureLog.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorsTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleFileListenerTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleTcpListenerTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs, tests/integration-tests/helix-payloads/cli-integration-tests.sh
This PR fixes #196 and refactors the AppRunner formerly from Xamarin to enable better logging, easier debugging, fixes some small bugs and splits large methods.
- Refactor `AppRunner`
- Split very long methods by Device/Simulator bound logic
- Separate logic for test orchestration with mlaunch argument preparation
- Dispose logs/listeners correctly
- Look for devices before we start the listeners and log capturers
- Improved unit test readability where the most important part (mlaunch arg checking) is now easier to read and safe to make changes when logic changes
- Improve finding simulators:
- Enable nullability for `BlockingEnumerable`, `SimulatorLoader` and connected POCO classes
- Improve error messages
- Make `SimulatorLoader` retry listing devices as that might fail occasionally
- …
=> [iOS] Refactor AppRunner

tests/integration-tests/helix-payloads/cli-integration-tests.sh, tests/integration-tests/helix-payloads/simulatorinstaller-integration-tests.sh
This changes how we install the dotnet tools that are being tested during our integration testing.
We won't need to purge the NuGet cache anymore so this also fixes #123.
=> Install the dotnet tools via --tool-path in our CI tests

src/Microsoft.DotNet.XHarness.TestRunners.Common/Microsoft.DotNet.XHarness.TestRunners.Common.csproj
Else we will have issues like the following one:
```
error NU1101: Unable to find package Microsoft.DotNet.XHarness.TestRunners.Common. No packages exist with this id in source(s): dotnet-eng, dotnet-tools, dotnet5, dotnet5-transport, nuget.org
```
=> [Runners] Do publish the Common pkg.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/TestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestCommand.cs
There are several javascript engines (e.g. v8, javascriptcore etc) which wasm tests can run on currently  and this list might be extended. Each of js engine can have (potentially different) set of arguments. e.g.
`v8 --expose_wasm runtime.js -- --enable-gc --run WasmTestRunner.dll System.Buffers.Tests.dll`
So the idea is to run the wasm runner inside of the wasm app by starting a js engine as a process and pass in respective arguments, in particular test runner and test assembly name.
This change is simplified version of what we want to get in the end.
cc @akoeplinger @steveisok
=> [wasm] Add running wasm tests as a process starting a javascript engine with arguments

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, src/Microsoft.DotNet.XHarness.CLI/runtimeconfig.template.json, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/Microsoft.DotNet.XHarness.SimulatorInstaller.csproj, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/runtimeconfig.template.json
This is a better way than https://github.com/dotnet/xharness/pull/30 since .NET Core 3.1 added an official msbuild property for setting that value.
=> Use RollForward msbuild property instead of rollForwardOnNoCandidateFx in json

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
This takes about 3mins and is useless since we don't support a way to select a single theory test case to be run.
The official xunit console runner also disables this.
Additionally added a small fix to make sure the result xml has the correct xml header.
=> WASM: don't preenumerate Theories during xunit test discovery

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/ISimulatorDevice.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestTarget.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs, src/Microsoft.DotNet.XHarness.iOS/AppInstaller.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorsTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppInstallerTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
- Allow to specify for example `ios-simulator-64_13.4` as test target
- When no version is specified (only `ios-simulator-64`), find the first suitable Simulator
- Xamarin functionality not changed
=> Allow to specify desired Simulator runtime (iOS/tvOS/WatchOS version)

src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResultParser.cs
If all tests are ignored, return 0 exit code.
Fixes: #258 
```
info: test[0]
Starting test for ios-simulator-64..
info: test[0]
Starting application 'System.Globalization.Tests' on ios-simulator-64
info: test[0]
Application finished the test run successfully
info: test[0]
Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0
XHarness exit code: 0
```
=> [iOS] Do not fail if 0 tests were run

src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSPackageCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs, src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs, src/Microsoft.DotNet.XHarness.Common/Logging/NullLog.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/ConsoleLog.cs
- Stop logging `ps aux` output because the logs are hard to read with the ps output and it brings no value really
- Introduce the `NullLog` and use it where we don't care about process outputs
- Make ConsoleLog thread-safe
=> Improve logging experience (add NullLog, ConsoleLog thread-safe, ps aux not logged)

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
`LoadDevices` is called internally inside `SimulatorLoader`. The only reason it stays public is for Xamarin flows.
=> [iOS] Improve simulator loading

src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
We hit an issue in the wasm testing in dotnet/runtime where xharness would exit with 0 failed tests but the testResult.xml was empty.
This happens because we get the xml by reading stdout from the JS engine, but if xharness exits quickly enough the stdout event isn't handled anymore.
The documentation for the Process class mentions that you need to call WaitForExit() to make sure these events are called: See remarks in https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netcore-3.1#System_Diagnostics_Process_WaitForExit_System_Int32_
=> Make sure redirected stdout events are finished in ProcessManager

azure-pipelines.yml
Internal builds will now only run on OSX since running on both Windows and OSX was causing problems with Arcade trying to push to BAR twice as can be seen here:
https://dev.azure.com/dnceng/internal/_build/results?buildId=747943&view=logs&j=74e82b2b-41b5-505f-7026-605948fa01e2&t=45774f52-cdc2-5894-6dc7-2cfd734f27bf
I decided to keep OSX and not Windows leg since we test artifacts from OSX in our PR integration tests
=> Remove Windows build leg from internal builds

azure-pipelines.yml
Attempt to fix #286 
Also removes duplicate upload of AzDO logs as artifacts
=> Ignore unused ADB files when scanning for Component Governance

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorLoaderTests.cs
The bug this is fixing:
1. We are looking for suitable simulators
2. mlaunch fails to fetch the list of simulators
3. We nonetheless mark the state as loaded even though we are throwing
4. Logic above will retry
5. Since we marked the state as loaded, the second attempt to get us a simulator will not find it in the lists of devices in the memory and will try to create it then
6. Create fails because simulator with the same name exists already
#283
=> Do not mark simulators as loaded when mlaunch fails

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
Required for https://github.com/dotnet/runtime/issues/38931
/cc @premun @mandel-macaque
=> WASM: Add pumping of timer queue to ThreadlessXunitTestRunner

eng/Signing.props
https://github.com/dotnet/xharness/pull/291 - introduced a change to
skip some 3rd party assemblies for the signing step, but this broke
because of a msbuild issue: https://github.com/dotnet/msbuild/issues/5445 .
- Essentially, it ended up removing *all* the items to sign.
=> Fix signing that broke with an earlier commit

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/HardwareDeviceLoaderTests.cs
Doing the same for devices as we did for simulators: #283
=> Do not mark HW devices as loaded when it fails

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
Through investigation, I found out that mlaunch takes 2-4 minutes to list devices on a cold start. After that, some cache is in effect and listing of devices takes 1-30 seconds.
If we do not complete the run, next attempt requires the same amount of time. So if the timeout wouldn't be sufficient, retry won't help.
Increasing this timeout will prevent occasional problems. I will also be deleting all created devices from our infrastructure to speed things up but it doesn't solve the underlying issue completely and that is still up for an investigation.
=> Increase the timeout for listing simulators

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestWebServerStartup.cs
By default, we only serve files with known MIME types, but that is an issue when dotnet library tests consume over a hundred different file extensions in their tests
=> [wasm] Allow serving of unknown files

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
The problem here is that these tests run very quickly, writing to the
console.log very fast, and selenium seems to not return the logs during
that time. So, when the tests are done, which is indicated by an html
element being set, we stop listening for more log messages.
And exit with the test exit code, but no output messages from the test
run.
Eg: `System.Data.Common`
=> [wasm-browser][tests] Fix issue with some tests exiting with no output

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestWebServerStartup.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
We use selenium to get the console logs from the browser, via
`chromedriver`. But in case of some test libraries (eg.
`System.Memory`), we get too many messages written to `console.log`,
which seems to stall the whole thing (probably, chrome is rate limiting
it).
Instead, we switch to using a websocket, which the test page connects
to, and redirects all the messages to that. (thanks to @lewing for the suggestion)
- So, the test page can connect to `ws://<server>/console`
- We also continue to check selenium for any other messages, or errors
that might show up
This allows the test output to show up much faster, and longer running
tests work fine.
Issues:
- If we exceed the timeout, then we want to shutdown the tests, but
selenium doesn't seem to be able to close the browser correctly
- it …
=> [wasm][tests] Fix timeout issues with `test-browser`

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
.. tests by throwing an exception.
Errors like:
`http://bla/ - Failed to load resource: net::ERR_NAME_NOT_RESOLVED)`
Note: I wasn't able to capture these in js itself, to pipe through the
console websocket. So, we get these from Selenium, and that can be out
of sync with the messages from the console websocket.
This was seen in tests for `System.XmlSchemaSet.Tests`. These errors
would get logged, but since we were throwing exceptions for them, the
result of all the tests would marked as `GENERAL_FAILURE`.
Note: In this case the errors are expected, but I'm not sure how to
differentiate these from other browser level errors that mean that the
whole thing has failed.
=> [wasm] Log browser level errors, instead of interrupting the

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
This changes the output from:
```
dbug: test-browser[0]
[FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpProtocolTests.GetAsync_InvalidStatusLine_ThrowsExceptionOnSocketsHttpHandler(responseString: "HTTP/1.1 200\tOK")
dbug: test-browser[0]
System.PlatformNotSupportedException : System.Net.Sockets is not supported on this platform.
```
.. to ..
```
dbug: test-browser[0]
[FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpProtocolTests.GetAsync_InvalidStatusLine_ThrowsExceptionOnSocketsHttpHandler(responseString: "HTTP/1.1 200\tOK")
dbug: test-browser[0]
System.PlatformNotSupportedException : System.Net.Sockets is not supported on this platform.
```
=> [wasm][tests] Remove extra newline from output, making it a bit tighter 

src/Microsoft.DotNet.XHarness.Android/Microsoft.DotNet.XHarness.Android.csproj, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs, src/Microsoft.DotNet.XHarness.Common/Microsoft.DotNet.XHarness.Common.csproj, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, tools/Microsoft.DotNet.XHarness.SimulatorInstaller/Microsoft.DotNet.XHarness.SimulatorInstaller.csproj
Don't show PASS/SKIP messages by default in the console log, unless verbose logging is enabled in xharness.
We capture all output and store it in the wasm-console.log file in the xharness output directory instead.
---
I got many requests from various dotnet team members to make the default wasm output more similar to the desktop xunit output, which only displays failed tests by default.
The wasm output now looks like this:
```
info: test[0] Discovering: System.Runtime.Handles.Tests.dll (method display = ClassAndMethod, method display options = None)
info: test[0] Discovered:  System.Runtime.Handles.Tests.dll (found 14 of 15 test cases)
info: test[0] Starting:    System.Runtime.Handles.Tests.dll
fail: test[0] [FAIL] SafeWaitHandleTests.SafeWaitHandle_False
info: test[0] Assert.False() …
```
=> Improve wasm test logging

src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestReporterTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Ensure that we use a boolean for the connected lambda else we have some
issues when executing on devices.
=> [iOS] Ensure that the launch callback is correctly chained.

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This fixes the following issue:
```
error HE0004: Could not load the framework 'IDEKit' (path: /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/IDEKit):
dlopen(/Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/IDEKit, 1): Library not loaded: @rpath/DVTAnalyticsKit.framework/Versions/A/DVTAnalyticsKit
Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/Versions/A/IDEKit 19:26:05.1635280
Reason: image not found
```
=> Bump mlaunch to version compatible with Xcode 12

eng/Version.Details.xml, global.json, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestWebServerStartup.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, tests/integration-tests/Android/Android.Helix.SDK.Tests.proj, tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj, tests/integration-tests/iOS/iOS.Helix.SDK.Tests.proj
We were pulling in Microsoft.AspNetCore 2.2 via a nuget PackageReference, but after upgrading Microsoft.Extensions.Logging in https://github.com/dotnet/xharness/pull/315 we saw the following error when using the "wasm test-browser" command:
```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
Heartbeat.OnHeartbeat
System.TypeLoadException: Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffset dateTime, Boolean quoted)
at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOffset dateTime, Boolean quoted)
at Microsoft.Net.Http.Headers.HeaderUtilities.FormatDate(DateTimeOff …
```
=> Use latest version of ASP.NET Core via FrameworkReference instead of nuget

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmLogMessage.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
This is done by accepting json messages from the test runtime.js, which
are of the form `{ method: 'console.debug', payload: 'foo bar' }`.
=> [wasm][tests] Log messages with correct log level

src/Microsoft.DotNet.XHarness.Common/Microsoft.DotNet.XHarness.Common.csproj, src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Compatibility/Nullable.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Microsoft.DotNet.XHarness.iOS.Shared.csproj
We need to consume the Shared library in `xamarin-macios` which targets **.NET Framework 4.7.2**. When creating the project in `dotnet/xharness` we made a mistake and targeted .NET Standard 2.1 instead while 4.7.2 needs 2.0.
Some of the APIs are not available so minor changes are needed.
=> Target .NET Standard 2.0 instead of 2.1 for code shared with Xamarin

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
This is necessary so we can run the runtime tests from dotnet/runtime since they use exit code 100 to signal "success".
=> Add option to set expected exit code for Android instrumentation

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
Check first whether the message can be JSON before trying to deserialize it. This avoids throwing a lot of JsonException's for non-JSON messages.
/cc @radical
=> WasmTestMessagesProcessor: Avoid throwing exception for non-JSON messages

src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs
We were missing a call to the parameter-less Process.WaitForExit() since the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=netcore-3.1#System_Diagnostics_Process_WaitForExit) state:
> This overload ensures that all processing has been completed, including the handling of asynchronous events for redirected standard output. You should use this overload after a call to the WaitForExit(Int32) overload when standard output has been redirected to asynchronous event handlers.
Should help with https://github.com/dotnet/xharness/issues/338
=> Correctly use Process.WaitForExit() in AdbProcessManager

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
When starting chrome via selenium+chromedriver, it seems to crash
inexplicably (https://github.com/dotnet/runtime/issues/43955).
As a workaround, let's retry that a few times.
Also, adds `--no-sandbox` from https://github.com/dotnet/xharness/pull/340 .
=> [wasm][test-browser] Retry launching chrome if it fails on startup

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
We've seen a few cases where we get `INSTRUMENTATION_RESULT: shortMsg=Process crashed.` and the adb log shows that the process crashed with a segmentation fault.
Android writes a crashdump into `/data/tombstones` but you can't just pull from there. Instead there's an adb command to create a bugreport which produces a .zip file with all sorts of info about the OS, including the tombstones.
See https://developer.android.com/studio/debug/bug-report.html
=> Run "adb bugreport" when instrumentation process crashes

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
This tries to handle new failures seen on CI after the last update to add verbose logging.
```
[13:08:27] crit: System.AggregateException: One or more errors occurred. (Cannot access a closed file.)
---> System.ObjectDisposedException: Cannot access a closed file.
at System.IO.FileStream.ValidateReadWriteArgs(Byte[] array, Int32 offset, Int32 count)
at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.WriteLine(String value)
at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.Invoke(String message) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 103
at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmBrowserTestRu …
```
=> [wasm][test-browser] Improve logging, and try to be more resilient to errors

src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/AppBundleInformationParserTests.cs
There are couple of NREs coming out of the extensions so turned them nullable and it uncovered many other potential issues.
This fixes finding app bundles in Xamarin using the custom `IAppBundleLocator`
=> Fix NREs in ProjectFileExtensions

src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs
This improves the experience when `xcode-select` points somewhere bad (like xcode command tools).
https://github.com/dotnet/xharness/issues/337
=> Improve error message when Xcode is not found

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmApplicationEntryPoint.cs
Make make the Run in the threadless runner and WasmApplicationEntry point async so that it can yield back to js to resolve promises correctly.  Depends on https://github.com/dotnet/runtime/pull/44045 helps fix https://github.com/dotnet/runtime/issues/43958
=> Wasm make *.Run async.

src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs
Shell was already doing this and logs were a bit confusing:
```
XHarness exit code: 1107
+ exit_code=83
```
=> Modulo the exit codes by 127 so they correspond with posix

src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/DeviceLogCapturer.cs, src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Full iOS simulator log can have 2+MB while we are interested only in the part when we were running the current app.
We also don't want logs from previous runs of different apps.
Also remove some dead code from device log capturer.
=> Dont capture entire iOS simulator logs, only during test

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
We have this output in a separate file, it is not as important and only clutters the logs.
=> Do not log the full XML when listing simulators

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
In some test runs, launching chromedriver failed
with (https://github.com/dotnet/runtime/issues/44862):
```
Connection refused Connection refused
Connection refused Connection refused
[00:03:37] crit: OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:37245/
at OpenQA.Selenium.DriverService.Start()
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
at …
```
=> [wasm][test-browser] Add another case for retrying chromedriver launch

src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
This makes log more readable for some cases where it wasn't clear what process that was (iOS, mlaunch, lldb...)
=> Log exiting process' name

src/Microsoft.DotNet.XHarness.iOS/ExitCodeDetector.cs
Remove namespace because it may be different
=> Fix regex for exit code detection

README.md
```
dotnet xharness
Could not execute because the specified command or file was not found.
Possible reasons for this include:
* You misspelled a built-in dotnet command.
* You intended to execute a .NET program, but dotnet-xharness does not exist.
* You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
I tried even `dotnet-xharness`.
Using the plain `xharness` works fine.
=> Use xharness tool directly

src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs, src/Microsoft.DotNet.XHarness.iOS/AppTester.cs
Log `ios-simulator-64_13.5` instead of `Microsoft.DotNet.XHarness.iOS.Shared.TestTargetOs`
=> Fix target name in logs

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/Execution/IAdbProcessManager.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
There seems to be a mystery state where the install cache is full or something, rebooting device helps.  
Also improve wait-for-device to actually check the boot_completed property (exposed by rebooting devices) and fix standard error logging bug pointed out by @akoeplinger that's been there forever.
Since the state is mysterious, I prototyped an "always reboot the device" version of Xharness and ran it several times [Sample log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/results-6eb79d1a38ae42e59a/xharness-reboot-testing-1/console.f2c8185b.log?sv=2019-07-07&se=2020-12-22T00%3A35%3A55Z&sr=c&sp=rl&sig=9as0prf6CjZ9nJmqpyxlEPszi57R7gV68qs%2B7EZ%2BFEw%3D) to be sure the concept here works (logging has been cleaned up a bit)
=> Address https://github.com/dotnet/runtime/issues/45428 

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
- Log arguments passed to chromedriver
- Log `driver.log` if the driver crashes
- Re-create ChromeDriverService, when we are retrying. This is because
the exception from a failed chromedriver can show up when creating a
`ChromeDriverService`, or `ChromeDriver`.
- And delete older `driver.log` before starting
=> [wasm][test-browser] Improve logging, and retrying

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs, src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs
- Make failure to pull files or enumerate devices fail instead of warning.
- Detect an alternative version of the broken pipe issue (same recourse)
- Fail, and introduce exit code for inability to enumerate devices ; we'll do an infra retry and reboot to recover from this in Arcade.
https://github.com/dotnet/xharness/issues/384
https://github.com/dotnet/xharness/issues/385
https://github.com/dotnet/xharness/issues/389
=> Fixes for Xharness issues 354(again), 385, and 389

README.md
During a discussion with a user on Discord we discovered that it's easy to accidentally install an old xharness version by copying the command from the README.
We can specify the `*` version so it'll download the latest one to avoid this.
=> Update README to install latest version

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
This pull request adds `--expected-exit-code` argument to the `wasm test` command. It will allow to validate the result of the wasm functional test as we do for other platforms (ios, android).
=> Add the expected exit code argument to the wasm test command

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Use `--browser=safari`
This uses `safaridriver`, and before the first use, it needs to be enabled with: `safaridriver --enable`.
See: https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari
=> [wasm] Add support for testing with Safari

src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/CaptureLog.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/LogFile.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Logging/CaptureLogTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Tests/ExitCodeDetectorTests.cs
This fixes #413 where we were detecting exit code from previous runs
=> Fix capture log to return stream reader from the right position

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Use --browser=firefox
- Requires gecko driver [Github repository of Mozilla](https://github.com/mozilla/geckodriver/releases)
Closes https://github.com/dotnet/runtime/issues/47038
=> [wasm] Add support for testing with Firefox

src/Microsoft.DotNet.XHarness.CLI/Program.cs
The order was changed in #412 and it is now "android, wasm, help, version, ios" which seems off
=> Reorder commands when doing `help`

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
The code for Edge, and Chrome is pretty much the same, except for the
concrete types, so sharing all that.
=> [wasm] test-browser: Add support for Edge

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
The min simulator that can be used in xcode12.5 and later has changed.
We need to bump it.
This is a quick fix but we should be able to support the desired version
from the API.
=> [iOS] Change the min sim for watchOS.

src/Microsoft.DotNet.XHarness.Apple/AppRunnerBase.cs
I found this problem when trying to run a runtime-built app on Helix
=> Make sure the MacCatalyst app's binary is executable

src/Microsoft.DotNet.XHarness.Apple/AppRunnerBase.cs, src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/AppleRunCommand.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/ExitCodeDetectorTests.cs
Before I dive into the investigations of why we get hangs when running the app's binary directly, we can have this solution that uses `open -w` and works in the Helix environment
This solution requires getting the exit code from the `system.log`
Resolves #462
=> Run MacCatalyst via `open w` and detect exit code from logs

src/Microsoft.DotNet.XHarness.Apple/AppRunnerBase.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/CaptureLog.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
I saw the `system.log` being empty which ends up with us not detecting the exit code.
Hopefully, this will go away when we start running the MacCatalyst binary directly and get the exit code directly too
=> Wait for MacCatalyst system.log flush

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
=> [wasm] add `--expected-exit-code` for `wasm test-browser`, similar to

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
This reverts commit 66b9a52dfea930ff2cfb588e5f2636932a1f6868.
Should have been in xcode/12.5 so lest remove it and do the right thing.
=> Revert "[iOS] Change the min sim for watchOS. (#443)"

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Sometimes starting the chromedriver can fail, and that can just be an
intermittent issue. For that reason, we have retry logic which is based
on check the `WebDriverException`'s message for certain strings.
But the way the driver service is created changed in
7a34cdfa5ddc304f40e063b02ced9a31b04691f7, to use reflection, which meant
that the `WebDriverException` is thrown wrapped in a
`TargetInvocationException`, which then breaks our retry checks.
```
[02:56:47] crit: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> OpenQA.Selenium.WebDriverException: Cannot start the driver service on http://localhost:39881/
at OpenQA.Selenium.DriverService.Start()
at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command …
```
=> [wasm] Fix browser launch retry logic for chrome/edge

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
The `Process.Start` doesn't find our JS engines on Windows when
process.StartInfo.UseShellExecute = false;
is set. So we need to pass full path to the js engine cmd script on Windows.
Otherwise we endup with errors like this one:
XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=C:\Users\rodo\git\runtime\artifacts\bin\System.Collections.Concurrent.Tests\net6.0-Debug\browser-wasm\AppBundle\xharness-output -- --run WasmTestRunner.dll System.Collections.Concurrent.Tests.dll -notrait category=OuterLoop -notrait category=failing
info: 22:49:48.1379578 Running v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Collections.Concurrent.Tests.dll -notrait category=OuterLoop …
=> [wasm] Search js engines in PATH

src/Microsoft.DotNet.XHarness.Apple/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppTester.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleAppRunArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleTestCommand.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
Adds a new option `--reset-simulator` to `apple test` and `apple run` commands that kills the simulator process and erases all of its data before running the application.
Resolves #507
=> Add Apple simulator reset option

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Simulators/FindCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Simulators/InstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/FindCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/ListCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
XHarness simulators command now also accepts target runtimes in the same format as test targets. These formats are now equivalent:
- `com.apple.pkg.iPhoneSimulatorSDK14_3`
- `ios-simulator_14.3`
There is also a breaking change for the `install` and `find` commands - we now accept the list of simulators as positional arguments instead of `--simulator` arguments. The new usage is this:
```
xharness apple simulators install ios-simulator_14.3 tvos-simulator_11.6
```
Resolves #478
=> Accept test targets when working with the simulators command

src/Microsoft.DotNet.XHarness.Apple/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppTester.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs
There was a bug where instead of forwarding them to mlaunch as its `-set-env` arg, we were setting them for the mlaunch process as env vars instead 
#493
=> Forward -set-env to mlaunch in apple run command

README.md, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleAppRunArguments.cs, src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs, src/Microsoft.DotNet.XHarness.Common/CLI/EnvironmentVariables.cs
This improves the dev inner loop when using XHarness CLI binary directly (not through the tool). You can specify the mlaunch path easily.
Also adds documentation for XHarness developers.
=> Accept mlaunch path in env variable

src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitFiltersCollection.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/iOSApplicationEntryPoint.cs, tests/Microsoft.DotNet.XHarness.TestRunners.Tests/xUnit/XUnitFiltersCollectionTests.cs
- Application entry points: configure test runner with current application options
- Android and iOS application entry points were running the tests and then trying to configure filters for the test run afterwards.
- XUnit test case filtering:
- Handle different test case filter types separately
- Use added filters to determine the default for include/exclude
- Add tests for XUnit test case filtering
cc @steveisok @jkoritzinsky
=> Fix configuration of test filtering in Android application test runner

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetDeviceCommandArguments.cs
Possibly related to why we see more arguments than we need (#431)
=> Fix arguments of `android device` command

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
New args:
- `--debugger=N` - translates to `--remote-debugging-port=N` for
chromium browsers
- `--no-incognito`
- `--no-headless`
- `--no-quit` - doesn't kill the browser, and doesn't exit xharness at
the end of tests.
Note: tested only with chrome, and vscode
=> [wasm] Add support for running in debugging mode

azure-pipelines.yml
We were not running it in PRs and so it was injected everywhere
=> Run Component Governance detection only once in PRs

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/AppRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
Resolves #468 
New parameter `launch-timeout` will wait for provided amount of second for device's full boot completion.
Available for commands `android install/test/run`
=> add android device launch timeout as a parameter

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
Addressed #476 
New parameter `--wifi` introduced:
- `--wifi [enable]` - switching wifi on
- `--wifi disable` - switching wifi off
- without this parameter no additional checks are providing as before
=> handle wifi status for android devices

azure-pipelines.yml
This should make our PRs faster because we usually wait a long time for the VM
=> Use hosted pool for Windows leg in PRs

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleAppRunArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleGetStateCommandArguments.cs, src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs
Code de-duplication + fix of the `apple state` command wasn't reading the env var
=> Unify how we get the default mlaunch path

src/Microsoft.DotNet.XHarness.Apple/AppTester.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
=> Prevent the "Local network access" dialog in iOS 14+

src/Microsoft.DotNet.XHarness.Apple/AppInstaller.cs, src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustRunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustTestOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleUninstallCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/IMlaunchProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/MlaunchProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/Logs.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppInstallerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppUninstallerTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/CrashSnapshotReporterTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/HardwareDeviceLoaderTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorLoaderTests.cs
- Do not log copy progress when installing app on a real device (20k+ lines)
- Log the output from device finding into a separate file
Resolves #540
=> Shorten the main log (app install + device finding)

Directory.Build.props, src/Microsoft.DotNet.XHarness.Android/Microsoft.DotNet.XHarness.Android.csproj, src/Microsoft.DotNet.XHarness.Apple/Microsoft.DotNet.XHarness.Apple.csproj, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, src/Microsoft.DotNet.XHarness.Common/Microsoft.DotNet.XHarness.Common.csproj, src/Microsoft.DotNet.XHarness.TestRunners.Common/Microsoft.DotNet.XHarness.TestRunners.Common.csproj, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/Microsoft.DotNet.XHarness.TestRunners.Xunit.csproj, src/Microsoft.DotNet.XHarness.iOS.Shared/Microsoft.DotNet.XHarness.iOS.Shared.csproj, tests/Microsoft.DotNet.XHarness.Android.Tests/Microsoft.DotNet.XHarness.Android.Tests.csproj, tests/Microsoft.DotNet.XHarness.Apple.Tests/Microsoft.DotNet.XHarness.Apple.Tests.csproj, tests/Microsoft.DotNet.XHarness.Common.Tests/Microsoft.DotNet.XHarness.Common.Tests.csproj, tests/Microsoft.DotNet.XHarness.TestRunners.Tests/Microsoft.DotNet.XHarness.TestRunners.Tests.csproj
Each project had its own property for the C# language.
It was a mix of C# 8 and 9. With a few projects not specifying the version at all (and hence taking the default for the SDK version).
This PR sets the C# version to 9.0 on the project's root `Directory.Build.props` and removes any other definition. This way the version can be controlled at a single location, and all projects are aligned.
=> centrally control csharp version

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/ApkHelper.cs
Adding the file name as a second argument to `FIleNotFoundException`.
I.e, before:
```
Unhandled exception. System.IO.FileNotFoundException: message
at Program.Main()
```
After:
```
Unhandled exception. System.IO.FileNotFoundException: message
File name: 'file_name'
at Program.Main()
```
It's helpful if the code handling the exception wants to deal with the file name. Otherwise it would nee to rely on the format of the message and parse it.
=> file exception has filename

src/Microsoft.DotNet.XHarness.TestRunners.Common/TcpTextWriter.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs
Before we were getting an `ArgumentNullException` since we returned null from `SelectHostName()`.
=> Improve logging when tunnel fails to connect to any hostname

src/Microsoft.DotNet.XHarness.Apple/AppTester.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
Reverts dotnet/xharness#560
The real issue was that the tunnel wasn't actually used. Tunnel will be fixed in a follow-up PR.
We should instead show a warning if they select iOS 14 and not to use the tunnel (#572)
=> Revert "Prevent the "Local network access" dialog in iOS 14+"

src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Extensions.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV2TestReportGenerator.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/TestReportGenerator.cs
This will hopefully not make xharness fail horribly like this:
Harness exception for 'Tests for 54A12529-0251-4766-82CA-349C3EDC1DA8': System.ArgumentException: '', hexadecimal value 0x01, is an invalid character.
at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar (System.Int32 ch, System.Char* pDst, System.Boolean entitize) [0x00026] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1420
at System.Xml.XmlEncodedRawTextWriter.WriteCDataSection (System.String text) [0x00251] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/referencesource/System.Xml/System/Xml/Core/XmlEncodedRawTextWriter.cs:1370 …
=> Handle exceptions when trying to write CData sections.

src/Microsoft.DotNet.XHarness.Apple/AppTester.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.Common/Logging/AggregatedLog.cs, src/Microsoft.DotNet.XHarness.Common/Logging/CallbackLog.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/TcpTextWriter.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/iOSApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/TcpTunnel.cs
- The port wasn't opened on the device so the tunnel was never connected properly
- Fixing multiple timestamps in logs (cascades of callback/aggregated logs)
- Fixing how we log details when waiting for connections
Resolves #570
Testing showed that mlaunch doesn't quit when app is finished though (#574)
=> Fix TCP tunnel

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
There is a bug in mlaunch and the `--stdout` argument doesn't do anything but I will fix it later.
Once it's fixed, we will be ready.
=> Redirect app output into a separate file for Apple device

azure-pipelines.yml, eng/e2e-test.yml, tests/integration-tests/Android/Android.CLI.Commands.Tests.proj, tests/integration-tests/Android/Android.Helix.SDK.Tests.proj, tests/integration-tests/Apple/Device.Tests.proj, tests/integration-tests/Apple/Simulator.Tests.proj, tests/integration-tests/Apple/SimulatorInstaller.Tests.proj, tests/integration-tests/Helix.SDK.configuration.props, tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
- Add YAML template for E2E test stages
- Pull common Helix SDK configuration into a props file
=> Deduplicate XML and YAML code in E2E tests

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidArchitecture.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetDeviceCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetDeviceCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
The first part of changes for #584. Before we choose only one detected architecture from .apk (if it's not provided explicitely). This PR will allow to continue looking for compatible devices if we detect more then one architecture from APK. Also I make it possible to provide `--device-arch` more than once.
=> Look for devices with any of detected from apk architectures

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/LogType.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
For an application with bundle ID `net.dot.Bundle.ID`, stores the logs in:
- `net.dot.Bundle.ID.log`
- `net.dot.Bundle.ID.err.log`
Since the names are static, user can then cat them if he chooses to.
Resolves #596
=> Capture application stdout and stderr in log files

src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
In order to enable testing POST requests with browser. 
For example in `System.Net.Http.Functional.Tests.SyncHttpHandler_PostScenarioTest`
Fixes: `Access to fetch at 'https://127.0.0.1:54065/VerifyUpload.ashx' from origin 'http://127.0.0.1:54064' has been blocked by CORS policy`
=> [wasm] Allow any CORS header from the browser

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs, src/Microsoft.DotNet.XHarness.Common/Utilities/DisposableList.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Collections/BlockingEnumerableCollection.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/ITestReporter.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleFileListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Logging/CaptureLog.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleFileListenerTest.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Listeners/SimpleTcpListenerTest.cs
=> Fix `IDisposable` pattern on `CaptureLog`, `SimpleListener` and `ILogs`

src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
Allow response headers to be visible in wasm/JS. 
To fix wasm tests https://github.com/dotnet/runtime/issues/53668
=> Allow CORS response expose headers

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/ErrorPatternScanner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
In some cases, the runtime might crash, for example, due to an
assertion. But the app continues to execute, causing v8/chrome to exit
with the expected exit code. This causes xharness to treat the tests as
passing, even though the runtime had crashed.
To catch such cases, this adds support for scanning the output for some
error patterns, and adds a new argument for `wasm test`, and `wasm
test-browser`:
`--error-patterns=<file>`
This expects a text file with one pattern per line. The first character
of the line is treated special:
'@': the rest of the line is a substring to be used as the pattern
(case insensitive)
'%': the rest of the line is a .net regex string
'#': ignore the line completely
Example patterns file:
```
%console.error: Unhandled *[Ee]xception
@== JS stack trace
```
- this …
=> [wasm] Add scanning test output for error patterns

src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleGetDeviceCommandsArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleGetStateCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleInstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleJustRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleJustTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleUninstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/IncludeWirelessArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/IAppleAppRunArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleGetDeviceCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleUninstallCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/Arguments.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IDeviceManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
Not searching for wireless devices saves 18 seconds per run. Default is now to not search for them.
Resolves #623
This is a breaking change in case you connect devices wirelessly (cc @mattleibow @PureWeen @akoeplinger @steveisok)
@mandel-macaque this is **not** a breaking change for Xamarin (shared code behaves the same)
=> Allow user to specify whether to search for wireless devices

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
On windows/helix I am getting this error:
[13:34:28] crit: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> OpenQA.Selenium.WebDriverException: unknown error: Chrome failed to start: crashed.
Add another snippet so that Activation is repeated when we get this
error.
=> [wasm] Add another error snippet

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleJustRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleJustTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustTestCommand.cs
Resetting the simulator doesn't make sense since we expect the application to be already installed
=> Remove `--reset-simulator` from `just-*` commands

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
Use mlaunch capability that can redirect the output. Do this for Simulators only so that `--signal-app-end` keeps working for devices
Fixes #653
=> Redirect simulator logs into a separate file

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/JavaScriptEngineArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
Added a `NodeJS` engine when running xharness.
I am adding NodeJS support to MONO WASM (dotnet/runtime) and so this change would facilitate the testing as well as future maintenance of this feature.
Exactly the same as V8 or any other JavaScript engine.
Example: `XHarness wasm test --app=. --output-directory=".\xharness-output" --engine=NodeJS  --js-file=runtime.js   --   --run WasmTestRunner.dll System.AppContext.Tests.dll  -notrait category=OuterLoop -notrait category=failing` (this command runs some of the tests in dotnet/runtime on NodeJS)
=> Added NodeJS Engine

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
It's already disabled for Browser and according to https://github.com/xunit/xunit/issues/1746#issuecomment-412313820 the theory pre-enumeration only makes sense for UI scenarios like VS test explorer, which doesn't apply for xharness.
This should also speed up test discovery: https://github.com/dotnet/runtime/pull/55643#issuecomment-880013700
=> Disable PreEnumerateTheories in default TestAssemblyConfiguration for iOS/Android

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/BackgroundThrottlingArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
new argument `--background-throttling` 
- to minimize browser and don't make it headless
- not prevent timer throttling via browser arguments
Only works for Chrome and Edge
=> [wasm] new argument --background-throttling

tools/run-e2e-test.sh
- Clean artifacts/packages before rebuilding
- Fix `--skip-build`
- Offer .proj options when no argument passed
=> Fix E2E test script

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetStateCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/ShowAdbPathArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Program.cs
Needed for https://github.com/dotnet/arcade/pull/7970 and for dotnet performance tests
Also drops "Get" from "*GetDevice" and "*GetState" commands to follow the rest of the commandset
=> Allow printing ADB path using `xharness android state --adb`

src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustRunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustTestOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs
Recognizes a bad state from a specific exit code and then exits with `SIMULATOR_FAILURE` exit code instead.
Prevents hangs when running the application.
Resolves https://github.com/dotnet/core-eng/issues/14799
> Note: This will make the machines reboot in Helix when the simulator is stuck in this state as we already reboot on `SIMULATOR_FAILURE`
=> Detect broken Simulator state when uninstalling the application

src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
- `.mjs` - ES6 module
- `.cjs` - commonJS module
So that the files could be hosted by xharness for tests.
=> [wasm] Add mime-type for alternate javascript file extensions

src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs
Unfortunately, I cannot retry copying the system log as the original path is already gone.
I also only saw this happen once. If we see this more, we will do more about this.
Resolves #751
=> Print better error message when detecting exit code

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
- TestResults.xml was not complete under some circumstances.
- Sometimes it happend that WASM exit code was written before last messages from Console.WriteLine.
- Add debug log lines when testResults.xml is found during WASM messages processing.
=> Fix console output flushing in WASM XUnit runner

src/Microsoft.DotNet.XHarness.Apple/ErrorKnowledgeBase.cs
As requested in https://github.com/dotnet/core-eng/issues/15004 .  This, I assume, is to allow the Arcade wrapper scripts to handle it more accurately.
=> Stop returning SIMULATOR_FAILURE (88) on failed uninstall

src/Microsoft.DotNet.XHarness.iOS.Shared/XmlResults/NUnitV3TestReportGenerator.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/NUnitV3SampleFailures.xml, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
After finding a test failure in the xml, we need to position the xml reader at
the end of that test failure before trying to read another test failure.
Otherwise we end up rendering only the first one, because the rest of the code
will be confused.
=> Fix an issue with parsing test failures in NUnit v3 test files

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
- deserialize and validate, format and save on xharness server side
- seralize to single console line -> webSocket single message
=> [wasm] workaround corrupted test results file

src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
I am not 100% convinced the 165 code there is a good signal for simulator issues. The latter one is.
=> Don't return SIMULATOR_FAILURE for failed preemptive uninstallation

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
My previous change writes file with `<?xml version="1.0" encoding="utf-16"?>` in otherwise UTF8 file.
=> [wasm] fix XML header encoding

azure-pipelines.yml
- XHarness is used on 10.15 the most
- We are being warned about 10.14 being deprecated even though we didn't specify 10.14 anywhere
=> Enforce the MacOS 10.15 pool

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Arguments/WebServerUseCrossOriginPolicyArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/IWebServerArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
Enabling the switch the webserver will serve all requests with these response headers
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
=> New switch "web-server-use-cop" for webserver to set Cross-Origin-Policy headers

tools/install-xharness.sh, tools/run-e2e-test.ps1, tools/run-e2e-test.sh
We already have a shell script for Linux/MacOS but we could use this when working with the repo on Windows
=> Add script for running E2E tests on Windows

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs, src/Microsoft.DotNet.XHarness.Android/Execution/Api23AndOlderReportManager.cs, src/Microsoft.DotNet.XHarness.Android/Execution/IAdbProcessManager.cs, src/Microsoft.DotNet.XHarness.Android/Execution/NewReportManager.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidAdbCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetStateCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidAdbCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidCommandSet.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Program.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
=> Add `android adb` command

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestExecutingResult.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestExecutingResultTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestReporterTests.cs
The shared Xamarin code allowed for a short window in-between the app being installed and launched but not having connected over TCP to XHarness' listener.
We add a more granular code that will describe this case so that we don't need to return `TIMED_OUT` when `--launch-timeout` occurs since `TIMED_OUT` means that tests themselves are running too long. This new launch timeout is then categorized as infra failure rather than user's fault.
Resolves #785
=> Detect app launch timeout on Apple

src/Microsoft.DotNet.XHarness.TestRunners.Common/AndroidApplicationEntryPointBase.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationOptions.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/LogWriter.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/WasmApplicationEntryPointBase.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/iOSApplicationEntryPointBase.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/AndroidApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XunitTestRunnerBase.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/iOSApplicationEntryPoint.cs
Today, xharness implements the `AndroidApplicationEntryPoint`, `iOSApplicationEntryPoint` and `WasmApplicationEntryPoint` classes as xunit-specific implementations. Additionally, the `WasmApplicationEntryPoint` type didn't derive at all from `ApplicationEntryPoint` and didn't have good customization points, so it wasn't possible to replace the runner with a different runner.
For the test refactoring work that @trylek and I are doing in dotnet/runtime to make the runtime tests run more like regular tests, we're using a custom source-generated test runner. As a result, we're going to have a test runner/executor that is not the Xunit-provided runner, but we'll need to provide custom runners for each platform to provide our filtering and test execution mechanisms.
To limit the number of …
=> Refactor target-specific ApplicationEntryPoint subclasses to have non-xunit-specific base classes

azure-pipelines.yml
Somehow this stopped working over the weekend:
https://dev.azure.com/dnceng/public/_build/results?buildId=1509819&view=results
=> Fix macOS-10.15 vmImage name

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetStateCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/UseJsonArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetDeviceCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Program.cs
Currently, we do not include device's architecture in diagnostic data but rather the first of a list of all supported archs by the device. This PR adds a new ADB call that queries for the actual architecture of the device.
Secondly, this PR brings the Android and Apple `state` commands on-par and allows to export Android state information as JSON too (useful for querying devices over Helix for example).
Fixes #794
=> Get Android device architecture for diagnostic data

tools/Install-XHarness.ps1
This prevents the user from not being able to run things. Similar instructions are already in the Linux script
=> Add `DOTNET_ROOT` instructions to `Install-XHarness.ps1`

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs
On Android API 30 we can't use "adb pull" directly due to permission issues, see https://github.com/dotnet/xharness/issues/385
As a workaround we copy the files to the temp directory on the device using "run-as" and pull from there
=> Add workaround for pulling files on Android API 30 emulators

src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/RunOrchestratorTests.cs
=> Return `RETURN_CODE_NOT_SET` when Apple app's exit code not found

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
`ThreadlessXunitTestRunner` writes lines like:
`[PASS] foo.testname(testargs)`
to the console, which gets parsed by `WasmTestMessageProcessor`. But if
the list of arguments contains a new line(eg. in data for
`System.Text.RegularExpressions` tests), then the output line gets written
as multiple lines to the console. And that results in the output looking
like:
```
[02:41:04] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
[02:41:04] info: abc, beginning: 0, length: 5, expectedSuccess: True, expectedValue: "a\nabc")
...
```
Each of those lines being the last part of the `[PASS] foo.testname(someargs, "\nabc, ..")`.
Instead, we escape the new line chars.
Partially fixes https://github.com/dotnet/xharness/issues/816
=> ThreadlessXunitTestRunner: Escape newlines in test result lines

src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
The exit code detector throws an exception when it fails to completely find the system log:
```
[02:27:32] fail: Application run failed:
System.Exception: Failed to detect application's exit code. The system log was empty / not found at /tmp/helix/working/A09F08E2/w/CB8C0AAA/uploads/iPhone X (iOS 15.0) - created by XHarness.log
at Microsoft.DotNet.XHarness.Apple.ExitCodeDetector.DetectExitCode(AppBundleInformation appBundleInfo, IReadableLog systemLog) in /_/src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs:line 38
at Microsoft.DotNet.XHarness.Apple.RunOrchestrator.ParseResult(IExitCodeDetector exitCodeDetector, Int32 expectedExitCode, AppBundleInformation appBundleInfo, ProcessExecutionResult result) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs:line …
```
=> Report `RETURN_CODE_NOT_SET` when exit code detection blows up

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/AndroidDevice.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidGetDeviceCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/ApiVersionArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/IAndroidAppRunArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Argument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Arguments/AppPathArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetDeviceCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidUninstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/IDiagnosticDataExtensions.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
Resolves #380 
Previously, we were only querying devices and one of their properties - list of supported architectures. We were then matching this against user's wishes.
However, we also sometimes want to query by installed apps and now newly also by desired API version. I expect more device properties to come soon.
This means we needed to revamp a little bit how we query and represent Android devices - we no longer represent them as dictionaries but rather a dedicated POCO. We now also don't need to query device's architecture additionally, we can ask `AdbRunner` to get it for us right away.
The `android device` command also no longer expects app - you can specify other device properties (API version, arch).
=> Refactor querying Android devices, allow specifying API version

src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
Notify the user before we figure out how to deal with #819
=> Warn about broken exit code detection in iOS 15+

src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs
I noticed following error in the [bump PR in xamarin-macios](https://github.com/xamarin/xamarin-macios/pull/14350):
```
[0x70000d4d3000:] EXCEPTION handling: System.Net.Sockets.SocketException: The socket is not connected
"<unnamed thread>" tid=0x70000d4d3000 this=0x109f11090 , thread handle : 0x600000561d00, state : not waiting
at System.Net.Sockets.Socket.Shutdown (System.Net.Sockets.SocketShutdown) [0x0003a] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/Socket.cs:2814
at Microsoft.DotNet.XHarness.iOS.Shared.Listeners.SimpleTcpListener.Stop () [0x00022] in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs:48
at Microsoft.DotNet.XHarness.iOS.Shared.Listeners.SimpleListener. …
```
=> Fix killing TCP server in netstandard 2.0

src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/ExitCodeDetectorTests.cs, tests/integration-tests/Apple/Device.iOS.Tests.proj, tests/integration-tests/Apple/Device.tvOS.Tests.proj, tests/integration-tests/Apple/Simulator.Tests.proj
- Adds detection of exit code from the `DOTNET.APP_EXIT_CODE` tag
- Adds detection of exit code of iOS/tvOS devices
- Adds E2E tests for exit code detection
- Adds more queues to Simulator testing (changes from #815)
Resolves #819
=> Fix exit code detection on Apple devices and iOS 15+ Simulators

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunnerBase.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustRunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleJustRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleRunCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/NoWaitArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppOperations/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/JustRunOrchestratorTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/RunOrchestratorTests.cs
- Devices were easy (mlaunch has `--wait-for-exit`)
- MacCatalyst was easy (there is `-W`)
- Simulators were a bit more work because we need to wait for the launch to finish and only then we can quit
Resolves #846
=> Add the `--no-wait` switch to `just-run` and `run` command

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunnerBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppOperations/AppRunnerTests.cs, tests/integration-tests/Apple/Simulator.Tests.proj, tests/integration-tests/Apple/TestAppBundle.proj
This uses the same method to pull application logs as iOS simulator and gets the exit code from the stdout of the app that logs it from the [dotnet/runtime wrapper](https://github.com/dotnet/runtime/blob/a883caa0803778084167b978281c34db8e753246/src/tasks/AppleAppBuilder/Templates/runtime.m).
Resolves #848
=> Use `log stream` to capture MacCatalyst logs

src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/TestOrchestratorTests.cs
Some operations do not accept the cancellation token (but they are shared with Xamarin so cannot change this) and some operations do not throw but return a "timed out" result.
This change takes that into account and returns `APP_LAUNCH_FAILURE` if we time out before we reach app start.
Fixes #855
=> Handle token cancellation in between Apple operations

src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
This case, when app already connected over TCP, means, we already had a successful launch and we should categorize it as `APP_CRASH` so that the work item is not retried. This most likely means the runtime crashed while executing the tests
=> Clasify case when no XML results were sent as `APP_CRASH`

src/Microsoft.DotNet.XHarness.iOS.Shared/CrashSnapshotReporter.cs
=> Improve logging when copying Apple crash reports

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
Turns out `Path.Combine('/data/local/tmp', 'runtime')` does very cursed things if xharness is running on Windows (i.e. `/data/local/tmp\\runtime`). So, manually combine paths passed to Android. Also, Windows gets rid of UNIX permissions, so do the chmod on device, not during the build.
=> Don't use Path.Combine to create Android paths

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Since XHarness is multi-targeting, the mlaunch nuget is called multiple times in parallel which can lead to race conditions and errors like this:
> ##[error].packages/microsoft.dotnet.mlaunch/13.3.0-22255.12.9e3f1f1440/build/Microsoft.DotNet.Mlaunch.targets(4,5): error MSB3026: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not copy "/Users/runner/work/1/s/.packages/microsoft.dotnet.mlaunch/13.3.0-22255.12.9e3f1f1440/build/../mlaunch/lib/mlaunch/mlaunch.app/Contents/MonoBundle/System.Core.dll" to "/Users/runner/work/1/s/artifacts/obj/Microsoft.DotNet.XHarness.CLI//mlaunch/lib/mlaunch/mlaunch.app/Contents/MonoBundle/System.Core.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/Users/runner/work/1/s/artifacts/obj/Microsoft.DotNet.XHarness.CLI/mlaunch/lib/mlaunch/mlaunch.ap …
=> Only extract mlaunch once per build

tests/integration-tests/Apple/Simulator.Scouting.Tests.proj
This test project will be used when testing new Xcode. It is linked to [from the wiki](https://dev.azure.com/dnceng/internal/_wiki/wikis/DNCEng%20Services%20Wiki/870/Install-new-version-of-Xcode-on-Helix-machines)
=> Add E2E tests for the scouting queue

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.Apple/ErrorKnowledgeBase.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppOperations/AppRunTestBase.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppOperations/AppRunnerTests.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/AppOperations/AppTesterTests.cs
- Bumping mlaunch
- Removing `--stdout` and `--stderr` because new mlaunch changed behaviour around them but we also don't really utilize them as we use `log stream` instead
- Adding new failures to error knowledge base
=> Bump mlaunch to `13.3.0-22255.12.9e3f1f1440`

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
De-bumping because of failed launches. We will bump back once we handle #887
=> Un-bump mlaunch to `13.3.0-22181.16.cf9f7409e9`

src/Microsoft.DotNet.XHarness.Android/InstrumentationRunner.cs
=> Categorize Android emulator crash as `SIMULATOR_FAILURE`

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs
Resolves #910 
Adding tests for this would be super large change that would have to test many classes together so I didn't add one.
=> Categorize TCP race condition as `APP_LAUNCH_TIMEOUT`

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/TCCDatabase.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/TCCDatabaseTests.cs
This isn't a new permission, but for some reason it seems this becomes a problem in iOS 16 / Xcode 14 if it's not set (when it worked previously).
=> Give access to `kTCCServiceCamera` in simulator's TCC database

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
.. exiting. Recently, the log processor started using `Channel<T>` to
handle the messages, and this can sometimes mean that xharness exits
before all the messages have been processed.
It manifested sometimes in tests running successfully, but not writing a test
results file.
=> [wasm] Ensure the log messages get flushed out, on exit

src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
The 'ConnectedTask' must not only have completed, it must have completed successfully (run to completion) for a test to have started.
Fixes this type of exceptions:
Harness exception for 'introspection': System.AggregateException: One or more errors occurred. (A task was canceled.) ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029
at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] …
=> Fix logic to determine if a test has started execution

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/CompletionCallbackExecutionSink.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
Follow the same approach as in https://github.com/dotnet/xharness/pull/906
Should fix https://github.com/dotnet/xharness/issues/924
=> Use CompletionCallbackExecutionSink on Android/iOS too

src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
SpecialFolder Personal is the same value as MyDocuments. I am proposing to obsolete/deprecate SpecialFolder.Personal in https://github.com/dotnet/runtime/issues/75563. Since these two names have the same underlying value, it is more understandable/readable to use MyDocuments in code. This way readers fully understand what folder is being referenced.
Changing Personal to MyDocuments here.
=> Fix SpecialFolder.Personal usage

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
- Add `--no-sandbox` to chrome arguments when running in codespaces, or a container
- Don't fail if more than one `WASM EXIT` is received
=> [wasm] Misc improvements

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
.. has stopped running, so we don't miss any messages.
In some cases a wasm test app can emit `WASM EXIT` message more than once. First one triggers shutting down the whole thing, and any messages received after that can end up throwing because the message processor is no longer running.
Example failure:
```
[11:19:06] fail: 218355552
[11:19:06] info: WASM EXIT 1
[11:19:06] info: Waiting to flush log messages with a timeout of 120 secs ..
[11:19:06] info: WASM EXIT 1
fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HMKQV6N2NQ5F", Request id "0HMKQV6N2NQ5F:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Message processor is not running. Make sure to call RunAsync first
at …
```
=> [wasm] Don't throw if messages are received after the message processor

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
Porting https://github.com/xamarin/xamarin-macios/pull/15449/
Fixes https://github.com/dotnet/xharness/issues/923
=> [iOS] Adjust installing simulators according to recent Xcode14 changes

global.json, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
- if messages are received when the message processor isn't running, then log a warning once, instead of appending a `"message processor is not running"` to every message.
=> [wasm] Improve error handling in message processor

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This reverts commit fdf1b6b2e00e87c87be7b507297c8765d61b76a1.
This brings back xcode14 support
=> Revert "Bump mlaunch to `1.0.7+4e3eab455c` (#955)"

azure-pipelines-codeql.yml
Part of https://github.com/dotnet/arcade/issues/11151.  TSAEnabled is required for automated reporting
=> Fixup TSAEnabled variable to have a value for CodeQL runs

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/JavaScriptEngineLocationArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
.. which can be used to specify path to js engines, like V8.
=> [wasm] Add new `--js-engine-path` argument

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs, tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
Chatty is a service which tries to limit repeating entries in logcat output. This impacts us negatively more often than not as it will hide important entries that show what went wrong in a test.  This tries to disable chatty for all processes on the device.
Fixes https://github.com/dotnet/xharness/issues/937
=> Disable chatty on Android runs

src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
WebCIL is a new container format for .NET assemblies used when publishing WebAssembly apps (see https://github.com/dotnet/runtime/pull/79416)
Related to https://github.com/dotnet/runtime/issues/80807
=> Serve .webcil as application/octet-stream

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/LocaleArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
For https://github.com/dotnet/runtime/pull/80421/ we need tests to run with specific locale set, otherwise we won't be able to test the mechanism of loading different internationalization data based on the client's locale.
I added `-locale=xx-YY` flag that will set environment variable before the test on Browser / Node is launched. Default is "en-US".
=> Run tests with requested locale.

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs
Follow-up for #992.
I missed this change, without it `Locale` will be always passed to `WasmTest*Command` in the default form.
=> Fixing `Run tests with requested locale.`

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Follow up for https://github.com/dotnet/xharness/pull/992.
=> Fixing `Run tests with requested locale`.

src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs, tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/TestOrchestratorTests.cs
The TCP message, that we use to tell if TCP connection is to blame, can be faulty but once it connects, it's actually usually OK and the crash is an actual crash. This means we only have to categorize the result if the app never connects. It can still happen the app crashes and never connects and then we are not able to tell anyway.
The underlying issue with the TCP connection is still a problem somewhere in mlaunch and the real fix would have to come there but this PR improves categorization after https://github.com/dotnet/xharness/pull/987 was introduced.
https://github.com/dotnet/arcade/issues/11683
=> Categorize crash as TCP problem when connection never happens

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Arguments/WebServerUseDefaultFiles.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/IWebServerArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WebServerCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmCommandSet.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WebServerCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
- starts a webserver in the given app path
- waits till a timeout
- adds support for serving default files like `index.html`.
Prompted by need to run blazor published apps by starting a webserver for them
=> [wasm] Add a new `wasm webserver` command

azure-pipelines.yml
Failed here https://dev.azure.com/dnceng/internal/_build/results?buildId=2172601&view=logs&j=eacd36fa-ad88-57eb-d560-13c9c5f594cc
#1010
=> [release/6.0] Fix servicing pool name for internal builds

tests/integration-tests/Apple/helix-payloads/simulatorinstaller-integration-tests.sh
Newer simulator runtimes need authentication (see https://github.com/dotnet/xharness/pull/1044) which means we randomly get test failures.
=> Remove simulator URL testing from E2E tests

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/TCCDatabase.cs
Some bots give errors when we try to edit the db, if we fail creating the trigger, continue and hope that the privacy tool does work.
=> [iOS] TCCDatabase - even if we cannot create the trigger call the privacy tool

.config/tsaoptions.json
TSA violations are being assigned to the wrong service tree entry since TSA by default uses the area path to determine ownership, and the configured area path is a child of the .NET Framework service. We'd prefer not to change the area path, so let's try changing just the service tree id and see if that overrides TSA's default lookup logic.
The GUID `{4cac191f-8b27-4d55-abee-2eafb6470803}` corresponds specifically to the .NET Core service.
=> Set explicit service tree id in tsaoptions

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmLogMessage.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
Duplicate of https://github.com/dotnet/runtime/pull/91315
---
- Print arguments for forwarded console messages from browser to apphost console
- It matches the behavior with log to actual browser console
Previous
```
dbug: MONO_WASM [0x5f4244-main]: afterLoadWasmModuleToWorker added message event handler
```
New
```
dbug: MONO_WASM [0x5f4244-main]: afterLoadWasmModuleToWorker added message event handler {"workerID":1}
```
=> [wasm] Print message arguments in forwarded console

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Bumping the mlaunch version to pull in the fix: https://github.com/xamarin/maccore/pull/2709 which resolved an issue reported here: https://github.com/dotnet/xharness/issues/1075
=> Bump mlaunch to include a fix for ARM64 calling convention

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/AndroidHeadless/AndroidHeadlessInstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/AndroidHeadless/AndroidHeadlessRunCommand.cs
When an emulator/device doesn't boot (`sys.boot_completed` is not `1`) then it is generally not usable and we run into all sorts of failures like not being able to install APKs: https://github.com/dotnet/dnceng/issues/1448.
Fail early in cases like this and return `DEVICE_NOT_FOUND` exit code which will also trigger Helix infrastructure logic to e.g. reboot an emulator VM.
=> Fail early when Android device is not booted

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleStateCommand.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/Device.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IDevice.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IHardwareDevice.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Microsoft.DotNet.XHarness.iOS.Shared.csproj
When a device is not paired (trusted) then some data like the architecture is not available.
Prevent a NullReferenceException when trying to access that data.
Fixes https://github.com/dotnet/xharness/issues/1126
=> Apple: Fix NRE when listing devices that are not paired

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/Microsoft.DotNet.XHarness.TestRunners.Xunit.csproj, tests/Microsoft.DotNet.XHarness.TestRunners.Tests/Microsoft.DotNet.XHarness.TestRunners.Tests.csproj
This is how we do it for Microsoft.DotNet.XUnitConsoleRunner in arcade.
=> Distribute xunit.runner.utility for netcoreapp so we avoid NS1.x dependencies

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorSelector.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorLoaderTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/simulators.xml
Based on some investigation I did with Xcode 15.2 and previous, seems the device type that xharness creates is not allowed in more recent versions. 
By looking at what simulators I was able to create and that show up on Xcode 15.2 i think we want to use the SE 3rd generation as a base for old versions.
=> [iOS] Use a more modern device for XCode 15.2

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/EnvironmentVariables.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmThreadedTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmXmlResultWriter.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
- Switch between threadless and multi-threaded XUnit runner for WASM based on `IsThreadless` property
- The property will be set in the runtime based on passed flags and based on used runtime flavor
- Mutli-threaded runner extends the runner for other platforms and overrides how results are written (as single line)
- Add current thread id to STRT, PASS and FAIL messages when enabled with `XHARNESS_LOG_THREAD_ID`
Contributes to https://github.com/dotnet/runtime/issues/88763
=> [wasm] Switch between threadless and multi-threaded runner

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
DVTPlugInCompatibilityUUID is no longer available in the Info.plist so stop reading it. We only really used it for Xcode < 14 anyway.
Fixes https://github.com/dotnet/xharness/issues/1171
=> Support Xcode 15.3 simulators

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
change `--incognito` to `-private-window`
because `console.error: "Warning: unrecognized command line flag" "-incognito"` see [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-100697-merge-1b0bd685a6294b16af/WasmTestOnFirefox-ST-Wasm.Browser.Config.Sample/1/console.93426114.log?helixlogtype=result)
=> firefox fix -private-window

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This PR bumps the version of Android platform tools that we ship to `32.0.0`. 
The reason for this is that on older versions `adb` for MacOS was shipped only as `x86_64` executable, which is problematic if Rosetta is disabled on arm64 Mac devices on which xharness android commands are invoked.
Version `32.0.0` of Android tools: https://developer.android.com/tools/releases/platform-tools#3200_january_2022 has changed this limitation and `adb` now ships as the universal binary for Apple M1 devices.
---
Fixes https://github.com/dotnet/xharness/issues/1200
=> [android] Bump Android platform tools version to `32.0.0`

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
When we want to install simulators through xharness (via for example: `apple simulators install ios-simulator-64_17.2`) we first fetch simulator index file from Apple server. From that file we parse the available simulators and fetch the sources for their download. 
However, it can happen that for beta simulators Apple does not provide the `source` for download which currently breaks the xharness with:
```
crit: System.Exception: Source node not found
at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.SimulatorsCommand.GetAvailableSimulators() in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs:line 109
at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.InvokeInternal(ILogger logger) in …
```
=> [ios] Skip downloading simulators which don't have their source specified

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
Backport of: https://github.com/dotnet/xharness/pull/1211 to release/6.0
=> [release/6.0] [ios] Skip downloading simulators which don't have their source specified

src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
Backport of: https://github.com/dotnet/xharness/pull/1211 to release/8.0
=> [release/8.0] [ios] Skip downloading simulators which don't have their source specified

azure-pipelines-public.yml
AzDO will remove macos-11 later this month.
=> [release/8.0] Bump to macos-12 build image

azure-pipelines-public.yml
AzDO will remove macos-11 later this month.
=> [release/6.0] Bump to macos-12 build image

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Follow up for https://github.com/dotnet/xharness/pull/1221. In case of unsuccessful closing of tabs, we would end in infinite loop. Adding 10 sec timeout.
=> Prevent infinite loop when closing all tabs before quitting.

src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
The value changed in .NET 8: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix#change-description
This was touched in https://github.com/dotnet/xharness/pull/948 but the change is wrong, mlaunch expects this file to be in $HOME: https://github.com/xamarin/maccore/blob/bd1f42be1995b8501542a90671aa668771f1b3a0/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs#L341
=> Fix Environment.SpecialFolder.MyDocuments usage in BaseOrchestrator.cs

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Contributes to https://github.com/dotnet/runtime/issues/105370
=> don't crash when browser shutdown

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Follow up for https://github.com/dotnet/xharness/pull/1221.
Contributes to https://github.com/dotnet/runtime/issues/107466.
In https://github.com/dotnet/runtime/pull/107259 we discovered very frequent timeouts on Windows with newer chrome version, with logs:
```
[wasm test-browser] info: Closing 2 browser tabs before setting the main tab to config page and quitting.
[wasm test-browser] fail: Error while closing browser: System.InvalidOperationException: Sequence contains no elements
[wasm test-browser]          at System.Linq.ThrowHelper.ThrowNoElementsException()
[wasm test-browser]          at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestBrowserCommand.InvokeInternal(ILogger logger)
[wasm test-browser] XHarness exit code: 0
```
It suggests that in the try-catch block we're using …
=> Prevent "Sequence contains no elements" in browser tests

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
@ilonatommy I think we should backport the fix to release/9.0 too.
=> Simplify checking for last window in WasmTestBrowserCommand.cs

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Backport of: https://github.com/dotnet/xharness/pull/1261 and https://github.com/dotnet/xharness/pull/1262 to ` release/9.0`
=> Capture collection before using LINQ

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Contributes to https://github.com/dotnet/runtime/issues/107466 - when running locally with the new chrome we're getting:
```
[wasm test-browser] fail: Error while closing browser: OpenQA.Selenium.NoSuchWindowException: no such window: target window already closed
[wasm test-browser] from unknown error: web view not found
[wasm test-browser]   (Session info: chrome=128.0.6613.120)
[wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
[wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
[wasm test-browser]          at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
[wasm test-browser]          at …
```
=> Browser WBT on Chrome: avoid "no such window: target window already closed"

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
Found on https://github.com/dotnet/runtime/pull/107795.
Accessing `WindowHandles` when the browser is disconnected will always result in exception. We have to move all code that accesses it to try-catch. The code in `try` is the cleanup code, so it's fine if we enter it on disconnected driver.
Error being fixed:
[log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-107795-merge-f7b359a15e1941c3ab/WasmTestOnChrome-MT-System.Net.WebSockets.Client.Tests/1/console.8bfd054e.log?helixlogtype=result)
```
[15:41:09] fail: Application has finished with exit code TIMED_OUT but 0 was expected
[15:41:09] crit: OpenQA.Selenium.WebDriverException: An unknown exception was encountered sending an HTTP request to the remote WebDriver server for URL …
```
=> Access web driver's properties only in try-catch

.gitignore, Directory.Packages.props, azure-pipelines-public.yml, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/Simulator.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs, tests/integration-tests/Apple/Simulator.Commands.Tests.proj, tests/integration-tests/Apple/Simulator.Scouting.Commands.Tests.proj, tests/integration-tests/README.md
From Xcode 16 Apple stopped providing sources for downloading newer simulator runtime images. 
If we consider `watchOS 10.5 Simulator Runtime` and `iOS 18.0 beta Simulator Runtime` from https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex we can see that source is not provided for the latter:
```xml
<dict>
<key>authentication</key>
<string>virtual</string>
<key>category</key>
<string>simulator</string>
<key>contentType</key>
<string>diskImage</string>
<key>dictionaryVersion</key>
<integer>2</integer>
<key>fileSize</key>
<integer>3946536779</integer>
<key>identifier</key>
<string>com.apple.dmg.WatchSimulatorSDK10_5</string>
<key>name</key>
<string>watchOS 10.5 Simulator Runtime</string>
<key>platform</key>
<string>com.apple.platform.watchos</string> …
```
=> Support downloading and installing simulator images with Xcode 16

.gitignore, Directory.Packages.props, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/Simulator.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs, tests/integration-tests/Apple/Simulator.Scouting.Commands.Tests.proj, tests/integration-tests/README.md
Backport of: https://github.com/dotnet/xharness/pull/1277 to release/9.0
=> [release/9.0] Support downloading and installing simulator images with Xcode 16

.gitignore, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/Simulator.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj, tests/integration-tests/Apple/Simulator.Scouting.Commands.Tests.proj, tests/integration-tests/README.md
Backport of: https://github.com/dotnet/xharness/pull/1277 to release/8.0
=> [release/8.0] Support downloading and installing simulator images with Xcode 16

azure-pipelines-public.yml, src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
This PR adds functionality to check if a physical Android device is configured to correctly to allow debug APK installs.
Additionally, it prints out warning messages in cases the package verifier is not properly disabled which can lead to `INSTALL_FAILED_VERIFICATION_FAILURE` errors.
- If tests start failing again the warning message can be tracked with Build Analysis to record which Helix/tethered devices are affected
=> [android] Add warning message when Android devices have package verification enabled

src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs, src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs, src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/DeviceArchitectureArgument.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/TargetArgument.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs, src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs, src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs
This PR improves exception handling by following these rules:
- Don't use catch-all without logging or handling
- If a catch block re-throw, include inner exception
- If a catch block handles an exception, include logging
Fixes https://github.com/dotnet/xharness/issues/1247
=> Improve exception handling

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Since we are distributing OSS it is required to list all OSS dependencies in the generated SBOM manifest.
This can be accomplished by providing `cgmanifest.json` with custom entries which are not detectable by Component Governance (ref: https://docs.opensource.microsoft.com/tools/cg/component-detection/cgmanifest )
This PR adds a custom MSBuild task which list Android platform tools that we are distributing with xharness which is later properly included in the SBOM manifest (test in the official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2568115&view=results) 
SBOM manifest `manifest.spdx.json` from the linked official build:
```json
...
{
"name": "Android platform tools for Windows",
"SPDXID": "SPDXRef-Package-F3150E9103F8373C20F4E2F276D045725D67FD48DDD945AEB2033B …
```
=> [sdl] Include cgmanifest.json generation for Android platform tools to be included in SBOM generation

azure-pipelines-public.yml
macOS-12 image has been deprecated and we started getting:
```
##[error]The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
,##[error]The remote provider was unable to process the request.
```
in CI builds e.g.: https://dev.azure.com/dnceng-public/public/_build/results?buildId=859872&view=logs&j=15cba83b-cf63-5728-c708-eb441e2bd9e9
This PR bumps the build image version.
=> Bump macOS build image version

azure-pipelines-public.yml
Backport of https://github.com/dotnet/xharness/pull/1317 to release/9.0
=> [release/9.0] Bump macOS image version (#1317)

azure-pipelines-public.yml
Backport of https://github.com/dotnet/xharness/pull/1317 to release/8.0
=> [release/8.0] Bump macOS image version (#1317)

src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
Should fix https://github.com/dotnet/runtime/issues/108859.
In the tests running on newer .net we have `no-sandbox` passed to the browser. There are chrome user reports confirming that this fixes the issue. This flag was introduced in https://github.com/dotnet/xharness/pull/951, so while backporting I added both changes from the original PR: no sandbox + avoiding failures on multiple exit messages.
Backport of https://github.com/dotnet/xharness/pull/951 to release/6.0
CI
This is infa-only.
=> [release/6.0] Backport bypass OS security model + prevent failures on multiple exit messages

src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
We don't need to be on the latest TFM (we already set RollForward=major) and it prevents issues when xharness uses a newer SDK than runtime like in https://github.com/dotnet/runtime/pull/113381#issuecomment-2722131488
=> Stop building Microsoft.DotNet.XHarness.CLI for NetCurrent

tools/Install-XHarness.ps1, tools/install-xharness.sh
The dot.net redirector is currently having issues, we should be using the script directly from the CDN anyway.
=> Use dotnet-install script directly from CDN instead of dot.net

src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Arguments/WebServerUploadResults.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASI/WasiTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/IWebServerArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WebServerCommandArguments.cs, src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/ApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Common/TestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.NUnit/NUnitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmApplicationEntryPoint.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmThreadedTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmXmlResultWriter.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
- use HTTP POST when in available
- always single line otherwise
- `WebServerUploadResults` option, default true
- async `WriteResults`
Contributes to https://github.com/dotnet/runtime/issues/113474
=> [browser] HTTP POST test results when possible

tests/integration-tests/Apple/Simulator.Scouting.Tests.proj, tests/integration-tests/Apple/Simulator.Tests.proj
Update Apple simulator queues from `osx.1200.[amd64/arm64].open` to new macOS queues.
Contributes to https://github.com/dotnet/xharness/issues/1365.
On newer macOS version, MacCatalyst apps must be signed to be able tu run, see https://github.com/dotnet/xharness/issues/1376.
In this PR, we add a new signed test app, System.Collections.NonGeneric.Tests.app taken from dotnet/runtime CI and compressed using tar -czf to create a gzip archive. The compressed archive is uploaded as System.Collections.NonGeneric.Tests.app.zip to the remote storage.
Removing the old app maccatalyst-System.AppContext.Tests.app as there isn't 1:1 signed replacement which we could use after we migrate to newer osx queues.
Moving to `osx.15.amd64.open` and `osx.14.arm64.open` queues. Use `osx.14.arm64.open` queue …
=> [infra][apple] Update Apple simulator queues to OSX 14/15

tests/integration-tests/Apple/Simulator.Scouting.Tests.proj, tests/integration-tests/Apple/Simulator.Tests.proj
* use osx.15.amd64.open queue
* use osx.14.arm64.open queue Use osx.14.x86_64.open queue until osx.15 has enough capacity for dotnet/runtime CI. We want to match the used queues in xharness to make sure we are testing the same thing.
* Replacing the MacCatalyst app to use `System.Collections.NonGeneric.Tests.app`
backport of https://github.com/dotnet/xharness/pull/1368
=> [release/9.0][infra][apple] Update Apple simulator queues to OSX 14/15 (#1368)

src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorSelector.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorLoaderTests.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/simulators.xml, tests/integration-tests/Apple/Simulator.Scouting.Tests.proj, tests/integration-tests/Apple/Simulator.Tests.proj
backport of https://github.com/dotnet/xharness/pull/1368:
* use osx.15.amd64.open queue
* use osx.14.arm64.open queue Use osx.14.x86_64.open queue until osx.15 has enough capacity for dotnet/runtime CI. We want to match the used queues in xharness to make sure we are testing the same thing.
* Replacing the MacCatalyst app to use `System.Collections.NonGeneric.Tests.app`
Another change:
* Fix simulator selector to look for iPhone XS instead of iPhone X.
=> [release/8.0][infra][apple] Update Apple simulator queues to OSX 14/15 (#1368)

azure-pipelines.yml, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleHttpListener.cs
This PR includes backports for improving compliance into release/9.0 branch of the following PRs:
- https://github.com/dotnet/xharness/pull/1394 for properly enabling and triggering binskim runs on xharness artifacts
- https://github.com/dotnet/xharness/pull/1397 CodeQL warning fixes
=> [release/9.0] Backports for compliance improvements 

azure-pipelines.yml, src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleHttpListener.cs
This PR includes backports for improving compliance into release/8.0 branch of the following PRs:
- https://github.com/dotnet/xharness/pull/1394 for properly enabling and triggering binskim runs on xharness artifacts
- https://github.com/dotnet/xharness/pull/1397 CodeQL warning fixes
=> [release/8.0] Backports for compliance improvements

src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmThreadedTestRunner.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmXmlResultWriter.cs, src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
Because [System.Private.Xml.Tests](https://helixr1107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-115000-merge-f3e9e25dad9b4e958b/WasmTestOnChrome-ST-System.Private.Xml.Tests/1/console.8628b1e9.log?helixlogtype=result)
```
[19:06:40] fail: MONO_WASM: Out of memory
at System.IO.MemoryStream.set_Capacity(Int32 value)
at System.Xml.Linq.XElement.Save(Stream stream)
at Microsoft.DotNet.XHarness.TestRunners.Xunit.WasmXmlResultWriter.WriteResultsToFile(XElement assembliesElement)
```
=> [xunit] GC before XML serialization of results

.github/workflows/copilot-setup-steps.yml
This doesn't actually work as an env var, it needs to be set as a GitHub Actions variable in the repository settings: https://github.com/orgs/community/discussions/163374
I added the variable and it seems to have helped Copilot access the feeds.
Also only do a restore in copilot-setup-steps.yml to make sure a build error doesn't break Copilot
=> Remove firewall setting from copilot-setup-steps.yml

azure-pipelines.yml
I noticed a couple official builds hit the 60min default timeout.
=> Bump timeout in azure-pipelines.yml

src/Microsoft.DotNet.XHarness.Android/InstrumentationRunner.cs, src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppTester.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/IResultFileHandler.cs, src/Microsoft.DotNet.XHarness.iOS.Shared/ResultFileHandler.cs, tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/ResultFileHandlerTests.cs
This PR removes the cancellation token from `CopyResultsAsync`. When `--signal-app-end` is used, the same cancellation token was shared, which caused the copy command to terminate as soon as the app was terminated.
The copy command is considered deterministic and does not require a cancellation token.
=> Remove cancellation token from `CopyResultsAsync`
