dotnet/xharness

- src/Microsoft.DotNet.XHarness.Android/AdbExitCodes.cs
- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommandArguments.cs
Remaining challenges:  It says it wrote stuff to  /storage/emulated/0/, but it didn't.  @mandel-macaque could you ask about this?
> Changes needed to actually run "Xamarin.Android.Bcl_Tests-Signed.apk"

- src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/ICommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/PackageCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/TestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/XHarnessCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/iOS/iOSPackageCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommandArguments.cs
There were several bugs in the mess that I caused when I wrote the original validation where we for example ignored the bool coming out of the base validation.
This quick fix should make things more simple before we start implementing the whole iOS part.
> Fix argument validation

- src/Microsoft.DotNet.XHarness.iOS.Shared/Microsoft.DotNet.XHarness.iOS.Shared.csproj
Publish the library so that it can be consumed by other project,
specially xamarin/xamarin-macios.
> [iOS] Publish the shared lib of iOS as a nuget.

- src/Microsoft.DotNet.XHarness.CLI/Android/AndroidGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/ExitCode.cs
- src/Microsoft.DotNet.XHarness.CLI/Common/XHarnessCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/iOS/iOSGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/iOS/iOSPackageCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/iOS/iOSTestCommand.cs
We are already casting ExitCode everywhere so let's enforce it through the API
> Change Command return values to ExitCode

- eng/download-mlaunch.ps1
- eng/download-mlaunch.sh
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This will give us line numbers and other things when mlaunch crashes
Should help debugging #69
> Keep mlaunch pdbs/mdb for Debug XHarness package

- azure-pipelines.yml
We were broken by Arcade so here's a workaround before they fix it
More info: https://github.com/dotnet/arcade/issues/5328
> Disable signing validation to unblock the pipeline

- src/Microsoft.DotNet.XHarness.CLI/Properties/launchSettings.json
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleFileListener.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleHttpListener.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListenerFactory.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
As mentioned here: https://github.com/dotnet/xharness/issues/91#issuecomment-619859563, we include some garbage in the results XML
> Clean-up SimpleListeners and fix invalid XML header

- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/Issue95.xml
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/XmlResultParserTests.cs
Add a test to make sure that when there are skipped tests those are
correctly reported.
> [iOS][Tests] Add test to make sure that the skipped count is correct.

- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleTcpListener.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
> [iOS] Fix hangs when stopping the TCP listener

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSPackageCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSPackageCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/ExitCode.cs
Fixes: https://github.com/dotnet/xharness/issues/104
> [iOS] Make dotnet path configurable

- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
fixes: https://github.com/dotnet/xharness/issues/115
> [iOS] Add missing string interpolation.

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
> Tweaks for ADB runner, also make device output path not required

- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/TcpTunnel.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
Make sure that we do start the listeners with the tunnel.
fixes: #118
fixes: #119
> [iOS] Fix several tunnel issues.

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSGetStateCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/GetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/IProcessManager.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Execution/ProcessManager.cs
There was a hardcoded Xamarin.iOS dependent path in the GetState command
> [iOS] Fix state command to work with correct mlaunch & show mlaunch version

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/TestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/TestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/ExitCode.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
Fixes: https://github.com/dotnet/xharness/issues/114
> Apply xUnit exit code style and improve error logging

- eng/Publishing.props
- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
I am still testing, but making sure including the binary works right with SignTool stuff
> Adb linux support

- src/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs
- src/Microsoft.DotNet.XHarness.iOS/ErrorKnowledgeBase.cs
Same changes as present in
https://github.com/xamarin/xamarin-macios/pull/8502
> [iOS] Enable nullable in IKnowledgeBase

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
… and some minor timing issues noted while debugging it. 
Now always uses device serial when addressing devices because we can't call various APIs (e.g. "wait-for-device" in a multi-device space without it.
> Address https://github.com/dotnet/core-eng/issues/9820 

- src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
> Exit HandleTestFailed when SkipTestException is handled

- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs
I noticed that we never parse the arguments before we create the `Logger ` so we never actually print Debug/Trace. Also the factory was set up wrong so it wouldn't have worked
> Respect the verbosity level in logger

- azure-pipelines.yml
- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/ExitCode.cs
Still testing this out but this should solve https://github.com/dotnet/xharness/issues/177 and make it obvious to users when things crash.
> Address https://github.com/dotnet/xharness/issues/177

- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/GetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/TestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSPackageCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
Also fix the iOS test command help string
> Show descriptions for the help command

- src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationEntryPoint.cs
- src/Microsoft.DotNet.XHarness.Tests.Runners/ApplicationOptions.cs
- src/Microsoft.DotNet.XHarness.Tests.Runners/Core/TestRunner.cs
- src/Microsoft.DotNet.XHarness.Tests.Runners/Microsoft.DotNet.XHarness.Tests.Runners.csproj
- src/Microsoft.DotNet.XHarness.Tests.Runners/xUnit/XUnitTestRunner.cs
Remove the extra enums and use the ones in the common lib.
> [Runners/iOS/Android] Remove extra enums.

- src/Microsoft.DotNet.XHarness.iOS/ErrorKnowledgeBase.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/ErrorKnowledgeBaseTests.cs
This issue is very very rare and usually means that there is something
wrong either with the host or the device. The simplest way to fix this
is my rebooting the device. We now provide a nice message about it.
> [iOS] Notify the user when there are issues when connecting to the device.

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- remove usage of kill-server
- Wait longer for devices to come online
> Another attempt at handling offline devices

- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
> [iOS] Stop passing mlaunch output to stderr of XHarness CLI

- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
- src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/TestExecutingResult.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestExecutingResultTests.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestImporter/Templates/Managed/XamariniOSTemplateTest.cs
Fixes: https://github.com/dotnet/xharness/issues/143
Fixes code style for `TestReporter.cs`
> [iOS] Add LaunchFailure as one of the test run outcomes

- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/IErrorKnowledgeBase.cs
- src/Microsoft.DotNet.XHarness.iOS/ErrorKnowledgeBase.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/ErrorKnowledgeBaseTests.cs
Allow to provide a url to a knonw issue so that if we have a problem and
it has been reported the user can easily visit it for more informaiton.
> [iOS] Small refactor of the error knowledge base.

- XHarness.sln
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmCommandSet.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessHelpCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
- src/Microsoft.DotNet.XHarness.CLI/Program.cs
- src/Microsoft.DotNet.XHarness.WebAssembly/Microsoft.DotNet.XHarness.WebAssembly.csproj
- src/Microsoft.DotNet.XHarness.WebAssembly/xunit-runner.cs
From:
https://github.com/mono/mono/tree/master/sdks/wasm/xunit-runner
(I wasn't able to push to the Zoltan's branch in https://github.com/dotnet/xharness/pull/62)
> Add WebAssembly test runner.

- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Logging/LogFileTest.cs
> Fix flaky LogFile Tests

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/WasmApplicationEntryPoint.cs
> [wasm] Support getting XML test results and use proper arguments for different JS engines

- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/XUnitTestRunner.cs
After talking about the SkipTestException, we decided we are going to go
in a diff direction. Removing code that is not longer needed.
> [Runners] Remove SkipException test.

- src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Helpers.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
This started to fail today 100% of the time:
https://dev.azure.com/dnceng/public/_build/results?buildId=682330&view=ms.vss-test-web.build-test-results-tab&runId=21158168&resultId=100384&paneView=debug
> Fix unit tests relying on local IP addresses

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestCommand.cs
> Handle missing v8/jsc/sc binary gracefully

- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
Needs https://github.com/dotnet/runtime/pull/38690
/cc @premun
> WASM: Pump the threadpool while running tests so async Tasks work

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Getting logs fails with 3.141 and ChromeDriver 84
> Bump Selenium to 4.0.0 alpha

- README.md
Adresses https://github.com/dotnet/xharness/pull/315#discussion_r496673007
/cc @premun
> Update README with XHARNESS_LOG_TEST_START env var

- src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs
- tools/Microsoft.DotNet.XHarness.SimulatorInstaller/Commands/ListCommand.cs
> Keep multi-line logging for SimulatorInstaller

- azure-pipelines.yml
- eng/Publishing.props
https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3
Resolves #318
> Update package publishing to v3

- src/Microsoft.DotNet.XHarness.Common/Microsoft.DotNet.XHarness.Common.csproj
This is required for the iOS.Shared NuGet to work properly
> Publish the Common library as a NuGet

- src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/MtouchArchMissingEverywhere.xml
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Samples/MtouchArchMissingInConfiguration.xml
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Utilities/ProjectFileExtensionsTests.cs
Missing element should return `null` and not blow up
> Fix detection of MtouchArch

- src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Utilities/ProjectFileExtensionsTests.cs
Forward integration of https://github.com/xamarin/xamarin-macios/commit/ac36750f497ca2240865811cc46e0caef06caa75
> Look for Info.plist include in Link node

- src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/ProjectFileExtensions.cs
Forward integration of https://github.com/xamarin/xamarin-macios/commit/d4fb41b17270ef8f86fe10857e552d10e4f57b85
> FI Xamarin change to ProjectFileExtensions

- src/Microsoft.DotNet.XHarness.Android/AdbExitCodes.cs
- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
Seeks to address https://github.com/dotnet/xharness/issues/354
If this is insufficient there are some helix-based extra things to try, which I'll check out next week
> Add a retry in the case of exit code 224

- src/Microsoft.DotNet.XHarness.iOS/ExitCodeDetector.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/ExitCodeDetectorTests.cs
Probably just a temporary solution before we figure out how to read this using mlaunch
Resolves #364
> Add exit code detector

- eng/Versions.props
https://github.com/dotnet/core-eng/issues/11458
> Work around for SignCheckTask problem

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSAppRunArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSRunCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/iOS/iOSTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSAppCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSTestCommand.cs
Following how Android is handling it
> Add --expected-exit-code argument to the `ios run` command

- README.md
- tools/xharness-bootstrap.sh
Adds a simple script that installs XHarness locally in a folder so that you can try XHarness out easily.
> Add the XHarness bootstrap script

- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessHelpCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Program.cs
- src/Microsoft.DotNet.XHarness.CLI/Properties/launchSettings.json
This should fix https://github.com/dotnet/xharness/issues/67
> Throw error when calling ios commands on Windows or Linux

- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/iOSRunCommand.cs
- src/Microsoft.DotNet.XHarness.iOS/AppRunner.cs
- tests/Microsoft.DotNet.XHarness.iOS.Tests/AppRunnerTests.cs
When we fail to run the application ([example](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47039-merge-16bb7c3bb6434657a0/iOS.Simulator.Aot.Test/console.653e58e7.log?sv=2019-07-07&se=2021-02-04T12%3A22%3A12Z&sr=c&sp=rl&sig=d9J9JDSKNoO%2FVGyBtoMHjvGOokRJv7ohca4eMR%2BbWgM%3D)) in `ios test`, we return with 83 which is a signal for Arcade SDK to retry/reboot the work item.
For `ios run` this was broken and this was not detected at all. Further, it was still being compared to the value in `--expected-exit-code` ending up with a failure.
> Handle app run launch failure in `ios run`

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
Addresses https://github.com/dotnet/xharness/issues/430
> Correctly handle ADB timeouts when device calls fail, shorten timeout

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- tests/Microsoft.DotNet.XHarness.Android.Tests/AdbRunnerTests.cs
Addressed #434 
Ideas about what else should be added as Android unit tests are welcome
> Add more unit tests

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleAppRunArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleGetStateCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleRunCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/AppleAppCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/AppleGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/AppleRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/iOS/AppleTestCommand.cs
> Rename iOS arguments to Apple arguments

- src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/CrashSnapshotReporter.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/TestReporterTests.cs
Side effects of other work, related to #358
> Improve various logging

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
Resolves #458 
I decreased waiting time for any device from 5 to 3 min, just let me know if you think it should be longer/shorter
> Fail faster when cannot find any devices/emulators

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidRunCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidUninstallCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidUninstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Properties/launchSettings.json
> Allow to skip device-id for android install/run/uninstall

- src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs
> Do not report LaunchFailure when the app connected over TCP

- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleCommandSet.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleGetStateCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessHelpCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Program.cs
Forgotten folder back from #400
> Rename iOS namespace to Apple

- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
Resolves https://github.com/dotnet/core-eng/issues/12571
> Pass exit code after crash

- src/Microsoft.DotNet.XHarness.Apple/AppRunnerBase.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleGetDeviceArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleCommandSet.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleGetDeviceCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Program.cs
- src/Microsoft.DotNet.XHarness.Common/CLI/CommandArguments/XHarnessCommandArguments.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/AppInstallerTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/AppRunnerTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/AppTesterTests.cs
Adds a command that searches for a suitable simulator/device and returns its UDID
#493
> Add `apple device` command

- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs
> Fix Android logging for test and run commands

- eng/download-mlaunch.sh
Fixes a local dev experience when bumping mlaunch versions
> Remove previous mlaunch tags

- src/Microsoft.DotNet.XHarness.TestRunners.Common/TcpTextWriter.cs
- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/iOSApplicationEntryPoint.cs
This will make the app not hang indefinitely in case something happens to the host
This needs #579
> Timeout when waiting for TCP connection in TestRunner

- azure-pipelines.yml
- tests/integration-tests/Android/Android.CLI.Commands.Tests.proj
- tests/integration-tests/Apple/Device.Commands.Tests.proj
- tests/integration-tests/Apple/Device.Commands.Tests.proj.xml
- tests/integration-tests/Apple/Device.Tests.proj
- tests/integration-tests/Apple/Simulator.Commands.Tests.proj
Also adds device tests but comments them out
Won't be able to finish due to #590
> Add E2E tests for `device`, `just-run` and `just-test` commands

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.Apple/AppOperations/AppRunner.cs
- src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetDeviceCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.Common/CLI/NoDeviceFoundException.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Hardware/SimulatorLoaderTests.cs
fix exit code type when devices are not attached and authorized
resolved #549
> handle ADB_DEVICE_ENUMERATION_FAILURE

- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
https://github.com/dotnet/core-eng/issues/13068
https://github.com/dotnet/runtime/issues/52471
> Uninstall Apple apps before installing

- src/Microsoft.DotNet.XHarness.TestRunners.Common/TcpTextWriter.cs
- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/iOSApplicationEntryPoint.cs
Dumping some improvements I made in a working branch
- Improves the life cycle of the object so that it cannot be in an unitialized state and can be disposed better
- Added docs
- Improved exception messages
> Improve TcpTextWriter

- src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessHelpCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Program.cs
> Deprecate the `ios` command

- src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs
> Warn when not using TCP tunnel for iOS 14+

- src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustRunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustTestOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleCommandSet.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleJustTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleUninstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
- src/Microsoft.DotNet.XHarness.Common/CLI/Commands/XHarnessCommand.cs
This makes the Apple code testable (#552, #533)
> Use dependency injection for Apple commands

- azure-pipelines.yml
- tests/integration-tests/Apple/Device.Commands.Tests.proj
- tests/integration-tests/Apple/Device.iOS.Tests.proj
- tests/integration-tests/Apple/Device.tvOS.Tests.proj
- tests/integration-tests/Apple/Simulator.Commands.Tests.proj
Resolves #574
Resolves partially also #590
> Enable Apple device and CustomCommands E2E tests

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/TestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WebServer.cs
- adds web-server-use-https
- adds web-server-use-cors
Fixes https://github.com/dotnet/xharness/issues/626
> make HTTPS and CORS optional features

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
> Reboot device in case of installation failure

- eng/Version.Details.xml
- eng/common/sdl/execute-all-sdl-tools.ps1
- eng/common/sdl/init-sdl.ps1
- eng/common/sdl/run-sdl.ps1
- global.json
- tests/integration-tests/Apple/Device.Commands.Tests.proj
- tests/integration-tests/Apple/Simulator.Commands.Tests.proj
- tests/integration-tests/Apple/TestAppBundle.proj
- tools/xharness-bootstrap.sh
> Revert "[main] Update dependencies from dotnet/arcade and bump to .NET 6.0 preview 4"

- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustRunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/JustTestOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs
> Distinguish between preparation and cleanup uninstallation

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Argument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/DebuggerPortArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/NoHeadlessArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/NoIncognitoArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/NoQuitAppAtEndArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/NoQuitArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/WasmTestBrowserCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
- tests/Microsoft.DotNet.XHarness.CLI.Tests/CommandArguments/ArgumentTests.cs
- fix nullable debug port
- rename things
- fix double negation on `no-headless`, `no-incognito` and `no-quit`
> [wasm] Fix arguments regressions

- src/Microsoft.DotNet.XHarness.iOS.Shared/Utilities/Helpers.cs
Fixes #640 
I tested this on the machine that was problematic
> List local networks via `NetworkInterface.GetAllNetworkInterfaces()`

- src/Microsoft.DotNet.XHarness.iOS.Shared/CrashSnapshotReporter.cs
> Retry copying of Simulator crash reports

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/HideProgressArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Simulators/InstallCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs
Also show progress and allow to turn it off via `--hide-progress`
Fixes #631
> Fix downloading of large files when installing Simulators

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/DiagnosticsArgument.cs
> Remove conflicting `-d` option (WASM and diagnostics)

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
https://github.com/xamarin/xamarin-macios/pull/12675
> Bump mlaunch to xamarin/xamarin-macios#12675

- tests/integration-tests/Android/Commands.Tests.proj
- tests/integration-tests/Android/Simulator.Tests.proj
> Replace android.open by android.29.open in tests on ubuntu

- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidGetDeviceCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidRunCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleGetDeviceCommand.cs
- src/Microsoft.DotNet.XHarness.Common/CommandDiagnostics.cs
- tests/integration-tests/Android/Device.Tests.proj
- tests/integration-tests/Helix.SDK.configuration.props
We will need this flag later when detecting infra problems in Helix SDK
https://github.com/dotnet/arcade/issues/8109
> Provide simulator/device flag in diagnostics data

- tools/Install-XHarness.ps1
- tools/install-xharness.sh
> Add PowerShell version of the install script

- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/InstallOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/SimulatorResetOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/UninstallOrchestrator.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/AppleResetSimulatorCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleCommandSet.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleResetSimulatorCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommandSet.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorDevice.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/SimulatorResetOrchestratorTests.cs
> Add `apple simulators reset-simulator` command

- src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs
Optimize waiting on tests to finish in ThreadlessXunitTestRunner.
Instead of while loop with checking on ManualResetEvent every 1ms,
use TaskCompletionSource triggered from DelegatingExecutionSummarySink completed callback.
> Wait on task instead of while loop with 1ms delay.

- src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
Related to https://github.com/dotnet/runtime/issues/63572
> Bump timeout for querying `Info.plist`

- src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
Related to https://github.com/dotnet/runtime/issues/63572
> Add retries to `PlistBuddy` calls

- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs
- src/Microsoft.DotNet.XHarness.Common/CLI/ExitCode.cs
> Report `SIMULATOR_FAILURE` for timeout when bad state is detected

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
This could possible resolve some of the issues from #839
> Bump mlaunch to `13.3.0-22181.16.cf9f7409e9`

- src/Microsoft.DotNet.XHarness.Android/Microsoft.DotNet.XHarness.Android.csproj
- src/Microsoft.DotNet.XHarness.Apple/Microsoft.DotNet.XHarness.Apple.csproj
This shouldn't cost us anything and we won't have to always build twice for no reason
> Do not multi-target Apple and Android projects

- src/Microsoft.DotNet.XHarness.Apple/ErrorKnowledgeBase.cs
> Add knowledge base item for non-interactive user session

- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidInstallCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/AndroidTestCommandArguments.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidInstallCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Android/AndroidTestCommand.cs
- tests/integration-tests/Android/Commands.Tests.proj
> Notify user when apk and required architectures differ

- src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/TestOrchestrator.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IDeviceLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/ISimulatorLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/InstallOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/JustRunOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/JustTestOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/OrchestratorTestBase.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/RunOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/SimulatorResetOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/TestOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/UninstallOrchestratorTests.cs
> Make Apple device/simulator finding cancellable

- src/Microsoft.DotNet.XHarness.CLI/Commands/AndroidHeadless/AndroidHeadlessRunCommand.cs
Due to mistakes in how the conditionals were written, The test results and ADB log were only being pulled down when a job passed, not when it failed.
Reconcile this whole section a bit more, now we have a better understanding of how running jobs on Bionic looks & what capabilities are available outside the Android Instrumentation framework.
> [bionic] Pull testResults.xml when job fails as well as passes

- tests/integration-tests/Apple/Device.Commands.Tests.proj
- tests/integration-tests/Apple/Simulator.Commands.Tests.proj
- tests/integration-tests/Apple/TestAppBundle.proj
Resolves https://github.com/dotnet/xharness/issues/907
> Increase E2E test timeouts

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
This is useful for logging messages from web workers, in addition to the
main thread.
Also, fixes https://github.com/dotnet/xharness/issues/891 .
> [wasm] Add support for handling more than one console websocket

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
- tests/Microsoft.DotNet.XHarness.Android.Tests/Microsoft.DotNet.XHarness.Android.Tests.csproj
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Microsoft.DotNet.XHarness.Apple.Tests.csproj
- tests/Microsoft.DotNet.XHarness.CLI.Tests/Microsoft.DotNet.XHarness.CLI.Tests.csproj
- tests/Microsoft.DotNet.XHarness.Common.Tests/Microsoft.DotNet.XHarness.Common.Tests.csproj
- tests/Microsoft.DotNet.XHarness.TestRunners.Tests/Microsoft.DotNet.XHarness.TestRunners.Tests.csproj
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
Pin Newtonsoft.Json version to latest
> Pin Newtonsoft.Json version

- tests/integration-tests/Helix.SDK.configuration.props
Follow-up for #930 
Trying to dismiss this - https://dnceng.visualstudio.com/public/_componentGovernance/153358?_a=alerts&typeId=6951422&alerts-view-option=active
> Pin Newtonsoft.Json version in Helix test projects

- src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs
- src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/Device.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/IHardwareDevice.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/DeviceFinderTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/ExitCodeDetectorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/InstallOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/JustRunOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/JustTestOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/OrchestratorTestBase.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/RunOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/SimulatorResetOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/TestOrchestratorTests.cs
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Orchestration/UninstallOrchestratorTests.cs
https://github.com/dotnet/runtime/issues/75307
> Search for paired iOS/tvOS devices only

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASI/Engine/WasiTestCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.Common/Microsoft.DotNet.XHarness.Common.csproj
- src/Microsoft.DotNet.XHarness.Common/Utilities/FileUtils.cs
> [wasm] On windows look for .exe, .cmd, and .bat when searching for

- azure-pipelines.yml
We have a separate pipeline for it and it takes quite a long time on the official build.
> Disable CodeQL in main azure-pipelines.yml

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
- src/Microsoft.DotNet.XHarness.iOS.Shared/SdkVersions.cs
> Bump mlaunch and SdkVersions

- azure-pipelines.yml
https://github.com/dotnet/xharness/issues/1010
> Trigger PRs on release branches too

- azure-pipelines.yml
The old image doesn't exist anymore
> [release/7.0] Fix build image and TSA settings

- README.md
- azure-pipelines.yml
- eng/Versions.props
- tests/integration-tests/Helix.SDK.configuration.props
- tools/Install-XHarness.ps1
- tools/install-xharness.sh
- tools/run-e2e-test.ps1
- tools/run-e2e-test.sh
> Change XHarness versioning to match branches

- README.md
- azure-pipelines.yml
- eng/Versions.props
- tests/integration-tests/Helix.SDK.configuration.props
- tools/Install-XHarness.ps1
- tools/install-xharness.sh
- tools/run-e2e-test.ps1
- tools/run-e2e-test.sh
> [release/7.0] Change XHarness versioning to match branches

- azure-pipelines.yml
> [release/6.0] Fix build image and TSA settings (#1020)

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
- tests/Microsoft.DotNet.XHarness.Android.Tests/Microsoft.DotNet.XHarness.Android.Tests.csproj
- tests/Microsoft.DotNet.XHarness.Apple.Tests/Microsoft.DotNet.XHarness.Apple.Tests.csproj
- tests/Microsoft.DotNet.XHarness.CLI.Tests/Microsoft.DotNet.XHarness.CLI.Tests.csproj
- tests/Microsoft.DotNet.XHarness.Common.Tests/Microsoft.DotNet.XHarness.Common.Tests.csproj
- tests/Microsoft.DotNet.XHarness.TestRunners.Tests/Microsoft.DotNet.XHarness.TestRunners.Tests.csproj
- tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests/Microsoft.DotNet.XHarness.iOS.Shared.Tests.csproj
- tests/integration-tests/Helix.SDK.configuration.props
> Pin `Newtonsoft.Json` version to 13.0.1

- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/TCCDatabase.cs
There is a bug in the iOS simulator from apple in which it does not respect the permissions set by simtcl. This is an issue because the tool adds a record with the value 4 in the auth type/mode but the simulator only respects the permission when set with value 2. To fix it we are going to be adding a trigger than when it sees a new permission added with mode 4 it will update the row with value 2 so that the simulator does respect the settings.
> [iOS] Ensure that the TCC database will work with the Xcode15

- eng/Signing.props
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
> Bump mlaunch to latest version

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmTestBrowserCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
- src/Microsoft.DotNet.XHarness.Common/CommandDiagnostics.cs
Wasm engine used, and version where possible.
> [wasm] Add telemetry for wasm commands

- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Only use devicectl for iOS 17 or newer devices
> Bump mlaunch to get fix for older devices v2

- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorSelector.cs
> [iOS] Fix DeviceType for iOS17

- tests/integration-tests/Android/Commands.Tests.proj
- tests/integration-tests/Android/Simulator.Tests.proj
- tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
https://github.com/dotnet/dnceng/issues/952
> [release/7.0] Use Ubuntu 22.04 servicing queues

- tests/integration-tests/Android/Commands.Tests.proj
- tests/integration-tests/Android/Simulator.Tests.proj
- tests/integration-tests/WASM/WASM.Helix.SDK.Tests.proj
https://github.com/dotnet/dnceng/issues/952
> [release/6.0] Use Ubuntu 22.04 servicing queues

- Directory.Packages.props
Includes fix for https://github.com/xamarin/xamarin-macios/issues/19577
> Bump mlaunch to 1.0.94

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/JS/WasmTestCommand.cs
Make the detection softer, until we resolve detected cases
See https://github.com/dotnet/xharness/pull/1014#issuecomment-1860757910
> [browser] softer detection of `WASM EXIT`

- azure-pipelines-public.yml
- azure-pipelines.yml
- eng/common-variables.yml
Move public build to azure-pipelines-public.yml
> Add 1ES template for official build

- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
See https://github.com/dotnet/runtime/issues/101618
> [browser] improve disconnect handling

- README.md
- azure-pipelines-public.yml
- eng/Versions.props
- tools/Install-XHarness.ps1
- tools/install-xharness.sh
Fixes https://github.com/dotnet/xharness/issues/1253
/cc: @vitek-karas
> Bumping version number to 10.0.0

- docs/high-level-architecture.md
This PR lists platforms and commands in docs.
> List platforms and commands in docs

- src/Microsoft.DotNet.XHarness.Android/AdbRunner.cs
- src/Microsoft.DotNet.XHarness.Android/Execution/AdbProcessManager.cs
- src/Microsoft.DotNet.XHarness.Apple/ExitCodeDetector.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Android/Arguments/DeviceArchitectureArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/CommandArguments/Apple/Arguments/TargetArgument.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/SimulatorsCommand.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs
- src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs
- src/Microsoft.DotNet.XHarness.Common/Execution/MacOSProcessManager.cs
- src/Microsoft.DotNet.XHarness.Common/Execution/ProcessManager.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/AppBundleInformationParser.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/SimulatorLoader.cs
- src/Microsoft.DotNet.XHarness.iOS.Shared/Listeners/SimpleListener.cs
Backport of https://github.com/dotnet/xharness/pull/1302 to release/9.0
> [release/9.0] Improve exception handling

- azure-pipelines.yml
Enabling TSA and Policheck in the official build in the official builds.
> [sdl] Enable TSA and Policheck in the official build

- docs/integrity-check.md
Adding documentation about integrity of 3rd party dependencies.
---
Fixes #1243
> [sdl] Add documentation on integrity checks for 3rd party dependencies

- azure-pipelines.yml
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Backport of: https://github.com/dotnet/xharness/pull/1307 and https://github.com/dotnet/xharness/pull/1308 to release/9.0 branch
> [release/9.0] Backport SDL improvements

- azure-pipelines.yml
- src/Microsoft.DotNet.XHarness.CLI/Microsoft.DotNet.XHarness.CLI.csproj
Backport of: https://github.com/dotnet/xharness/pull/1307 and https://github.com/dotnet/xharness/pull/1308 to release/8.0 branch
> [release/8.0] Backport SDL improvements

- azure-pipelines.yml
Backport of https://github.com/dotnet/xharness/pull/1377 to release/8.0
> [release/8.0] Enable binskim (#1377)

- azure-pipelines.yml
Backport of https://github.com/dotnet/xharness/pull/1377 to release/9.0
> [release/9.0] Enable binskim (#1377)

- azure-pipelines.yml
Example of successful build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2681172&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=661ad66f-d4b2-5abe-469c-11e428062102
> [sdl] Use 1espt outputs for triggering binskim runs

- azure-pipelines.yml
- eng/pipelines/apiscan-steps.yml
This PR adds APIScan steps to the ES1 release pipeline as required per compliance.
The internal release pipeline has been successfully executed.
> Add APIScan steps to the ES1 release pipeline

- azure-pipelines.yml
- eng/pipelines/apiscan-steps.yml
Backport of https://github.com/dotnet/xharness/pull/1437
> [release/8.0] Add APIScan steps to the ES1 release pipeline
